# Generated by Django 5.2.17 on 2026-08-23 07:09

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=140, verbose_name='Cargo')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('voter_scope', models.CharField(choices=[('TODOS', 'Todos los estudiantes'), ('GRADO', 'Estudiantes de grados especificos'), ('GRUPO', 'Estudiantes del grupo'), ('DOCENTES', 'Docentes'), ('COMUNIDAD', 'Toda la comunidad')], default='TODOS', max_length=14, verbose_name='Electores habilitados')),
                ('max_selections', models.PositiveSmallIntegerField(default=1, verbose_name='Selecciones permitidas')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Cargo electoral',
                'verbose_name_plural': 'Cargos electorales',
                'db_table': 'election_candidacy',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('number', models.PositiveSmallIntegerField(default=1, verbose_name='Numero del tarjeton')),
                ('slogan', models.CharField(blank=True, max_length=200, verbose_name='Lema de campana')),
                ('proposals', models.TextField(blank=True, verbose_name='Propuestas')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='elections/candidates/', verbose_name='Fotografia')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Candidatura aprobada')),
                ('is_blank_vote', models.BooleanField(default=False, verbose_name='Opcion de voto en blanco')),
                ('votes_count', models.PositiveIntegerField(default=0, verbose_name='Votos')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'db_table': 'election_candidate',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=180, verbose_name='Nombre del proceso')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('start_at', models.DateTimeField(verbose_name='Apertura de votacion')),
                ('end_at', models.DateTimeField(verbose_name='Cierre de votacion')),
                ('status', models.CharField(choices=[('CONFIGURACION', 'En configuracion'), ('INSCRIPCIONES', 'Inscripciones abiertas'), ('CAMPANA', 'En campana'), ('ABIERTA', 'Votacion abierta'), ('CERRADA', 'Votacion cerrada'), ('PUBLICADA', 'Resultados publicados')], default='CONFIGURACION', max_length=14, verbose_name='Estado')),
                ('allow_blank_vote', models.BooleanField(default=True, verbose_name='Permite voto en blanco')),
                ('show_live_results', models.BooleanField(default=False, verbose_name='Mostrar resultados en vivo')),
                ('require_2fa', models.BooleanField(default=False, verbose_name='Exigir doble factor')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='elections/', verbose_name='Imagen del proceso')),
            ],
            options={
                'verbose_name': 'Proceso electoral',
                'verbose_name_plural': 'Procesos electorales',
                'db_table': 'election',
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='ElectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('votes', models.PositiveIntegerField(default=0, verbose_name='Votos obtenidos')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje')),
                ('position', models.PositiveSmallIntegerField(default=1, verbose_name='Posicion')),
                ('is_winner', models.BooleanField(default=False, verbose_name='Electo')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicado el')),
            ],
            options={
                'verbose_name': 'Resultado electoral',
                'verbose_name_plural': 'Resultados electorales',
                'db_table': 'election_result',
                'ordering': ['candidacy__order', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('voter_hash', models.CharField(db_index=True, max_length=64, verbose_name='Huella del elector')),
                ('voted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del voto')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Votos',
                'db_table': 'election_vote',
                'ordering': ['-voted_at'],
            },
        ),
        migrations.CreateModel(
            name='VoterRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('voter_hash', models.CharField(db_index=True, max_length=64, verbose_name='Huella del elector')),
                ('candidacies_voted', models.PositiveSmallIntegerField(default=0, verbose_name='Cargos votados')),
                ('completed', models.BooleanField(default=False, verbose_name='Voto completo')),
                ('voted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ultimo voto')),
            ],
            options={
                'verbose_name': 'Registro de elector',
                'verbose_name_plural': 'Censo electoral',
                'db_table': 'election_voter_registry',
            },
        ),
    ]
