# Generated by Django 5.2.17 on 2026-08-23 07:09

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('consecutive', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Consecutivo')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('content', models.TextField(blank=True, verbose_name='Contenido generado')),
                ('context_data', models.JSONField(blank=True, default=dict, verbose_name='Datos del contexto')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Emitido el')),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDO', 'Emitido'), ('APROBADO', 'Aprobado'), ('ANULADO', 'Anulado')], default='EMITIDO', max_length=10, verbose_name='Estado')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprobado el')),
                ('verification_code', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Codigo de verificacion')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/', verbose_name='Archivo')),
                ('print_count', models.PositiveSmallIntegerField(default=0, verbose_name='Impresiones')),
            ],
            options={
                'verbose_name': 'Documento emitido',
                'verbose_name_plural': 'Documentos emitidos',
                'db_table': 'document_issue',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=180, verbose_name='Nombre del documento')),
                ('kind', models.CharField(choices=[('CERTIFICADO', 'Certificado'), ('CONSTANCIA', 'Constancia'), ('ACTA', 'Acta'), ('DIPLOMA', 'Diploma'), ('CIRCULAR', 'Circular'), ('CONTRATO', 'Contrato de matricula'), ('PAZ_Y_SALVO', 'Paz y salvo'), ('CARNET', 'Carne estudiantil'), ('OTRO', 'Otro')], default='CERTIFICADO', max_length=14, verbose_name='Tipo')),
                ('body', models.TextField(blank=True, verbose_name='Cuerpo del documento (HTML)')),
                ('footer', models.TextField(blank=True, verbose_name='Pie del documento')),
                ('signatures', models.JSONField(blank=True, default=list, verbose_name='Firmas')),
                ('paper_size', models.CharField(choices=[('A4', 'A4'), ('LETTER', 'Carta'), ('LEGAL', 'Oficio')], default='LETTER', max_length=10, verbose_name='Tamano')),
                ('orientation', models.CharField(choices=[('P', 'Vertical'), ('L', 'Horizontal')], default='P', max_length=1, verbose_name='Orientacion')),
                ('requires_consecutive', models.BooleanField(default=True, verbose_name='Usa consecutivo')),
                ('consecutive_prefix', models.CharField(blank=True, max_length=16, verbose_name='Prefijo del consecutivo')),
                ('next_consecutive', models.PositiveIntegerField(default=1, verbose_name='Siguiente consecutivo')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='Requiere aprobacion')),
                ('show_qr', models.BooleanField(default=True, verbose_name='Incluir codigo QR de verificacion')),
            ],
            options={
                'verbose_name': 'Plantilla de documento',
                'verbose_name_plural': 'Plantillas de documentos',
                'db_table': 'document_template',
                'ordering': ['kind', 'name'],
            },
        ),
    ]
