# Generated by Django 5.2.17 on 2026-08-23 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0002_initial'),
        ('documents', '0001_initial'),
        ('institutions', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentissue',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_documents', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por'),
        ),
        migrations.AddField(
            model_name='documentissue',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='documentissue',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AddField(
            model_name='documentissue',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_documents', to=settings.AUTH_USER_MODEL, verbose_name='Emitido por'),
        ),
        migrations.AddField(
            model_name='documentissue',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_issues', to='students.student', verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='documentissue',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_issues', to='teachers.teacher', verbose_name='Docente'),
        ),
        migrations.AddField(
            model_name='documentissue',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_templates', to='configuration.reportheader', verbose_name='Encabezado'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='institutions.institution', verbose_name='Institucion'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='documentissue',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='documents.documenttemplate', verbose_name='Plantilla'),
        ),
    ]
