# Generated by Django 5.2.17 on 2026-08-23 07:09

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradeDecimalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('name', models.CharField(default='Configuracion de decimas', max_length=120, verbose_name='Nombre')),
                ('decimals', models.PositiveSmallIntegerField(default=1, verbose_name='Numero de decimales')),
                ('rounding_mode', models.CharField(choices=[('HALF_UP', 'Aproximacion normal (0.5 sube)'), ('DOWN', 'Truncar decimales'), ('UP_FROM', 'Aproximar desde una decima especifica'), ('NONE', 'Sin aproximacion')], default='HALF_UP', max_length=12, verbose_name='Modo de aproximacion')),
                ('round_from', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=4, verbose_name='Aproximar a partir de')),
                ('apply_to_period', models.BooleanField(default=True, verbose_name='Aplicar a notas de periodo')),
                ('apply_to_area', models.BooleanField(default=True, verbose_name='Aplicar a promedio de area')),
                ('apply_to_final', models.BooleanField(default=True, verbose_name='Aplicar a nota final')),
                ('minimum_grade', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, verbose_name='Nota minima')),
                ('maximum_grade', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='Nota maxima')),
                ('passing_grade', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5, verbose_name='Nota aprobatoria')),
                ('is_default', models.BooleanField(default=True, verbose_name='Configuracion por defecto')),
            ],
            options={
                'verbose_name': 'Configuracion de decimas',
                'verbose_name_plural': 'Decimas de notas',
                'db_table': 'configuration_grade_decimal',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('name', models.CharField(default='Encabezado principal', max_length=120, verbose_name='Nombre de la configuracion')),
                ('line_1', models.CharField(blank=True, max_length=200, verbose_name='Linea 1')),
                ('line_2', models.CharField(blank=True, max_length=200, verbose_name='Linea 2')),
                ('line_3', models.CharField(blank=True, max_length=200, verbose_name='Linea 3')),
                ('line_4', models.CharField(blank=True, max_length=200, verbose_name='Linea 4')),
                ('show_logo', models.BooleanField(default=True, verbose_name='Mostrar logotipo')),
                ('logo_position', models.CharField(choices=[('left', 'Izquierda'), ('center', 'Centro'), ('right', 'Derecha')], default='left', max_length=10, verbose_name='Posicion del logo')),
                ('show_seal', models.BooleanField(default=False, verbose_name='Mostrar sello')),
                ('footer_text', models.CharField(blank=True, max_length=240, verbose_name='Texto de pie de pagina')),
                ('show_page_numbers', models.BooleanField(default=True, verbose_name='Numerar paginas')),
                ('show_print_date', models.BooleanField(default=True, verbose_name='Mostrar fecha de impresion')),
                ('watermark', models.CharField(blank=True, max_length=80, verbose_name='Marca de agua')),
                ('paper_size', models.CharField(choices=[('A4', 'A4'), ('LETTER', 'Carta'), ('LEGAL', 'Oficio')], default='LETTER', max_length=10, verbose_name='Tamano de papel')),
                ('orientation', models.CharField(choices=[('P', 'Vertical'), ('L', 'Horizontal')], default='P', max_length=10, verbose_name='Orientacion')),
                ('margin_top', models.PositiveSmallIntegerField(default=15, verbose_name='Margen superior (mm)')),
                ('margin_bottom', models.PositiveSmallIntegerField(default=15, verbose_name='Margen inferior (mm)')),
                ('margin_left', models.PositiveSmallIntegerField(default=12, verbose_name='Margen izquierdo (mm)')),
                ('margin_right', models.PositiveSmallIntegerField(default=12, verbose_name='Margen derecho (mm)')),
                ('is_default', models.BooleanField(default=False, verbose_name='Encabezado por defecto')),
            ],
            options={
                'verbose_name': 'Encabezado de reportes',
                'verbose_name_plural': 'Encabezados de reportes',
                'db_table': 'configuration_report_header',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('key', models.CharField(max_length=80, unique=True, verbose_name='Clave')),
                ('label', models.CharField(max_length=160, verbose_name='Etiqueta')),
                ('value', models.TextField(blank=True, verbose_name='Valor')),
                ('value_type', models.CharField(choices=[('STRING', 'Texto'), ('INT', 'Numero entero'), ('DECIMAL', 'Numero decimal'), ('BOOL', 'Si / No'), ('JSON', 'JSON'), ('DATE', 'Fecha')], default='STRING', max_length=10, verbose_name='Tipo')),
                ('group', models.CharField(default='General', max_length=60, verbose_name='Grupo')),
                ('help_text', models.CharField(blank=True, max_length=240, verbose_name='Ayuda')),
                ('is_editable', models.BooleanField(default=True, verbose_name='Editable')),
            ],
            options={
                'verbose_name': 'Parametro del sistema',
                'verbose_name_plural': 'Parametros del sistema',
                'db_table': 'configuration_parameter',
                'ordering': ['group', 'label'],
            },
        ),
    ]
