# Generated by Django 5.2.17 on 2026-08-23 07:09

import core.authentication.models
import django.utils.timezone
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('event', models.CharField(choices=[('LOGIN', 'Inicio de sesion'), ('LOGOUT', 'Cierre de sesion'), ('2FA_OK', 'Verificacion 2FA'), ('2FA_FAIL', 'Fallo de verificacion 2FA'), ('PASSWORD_CHANGE', 'Cambio de contrasena'), ('PASSWORD_RESET', 'Recuperacion de contrasena'), ('LOCKED', 'Cuenta bloqueada')], db_index=True, max_length=24, verbose_name='Evento')),
                ('success', models.BooleanField(default=True, verbose_name='Exitoso')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=320, verbose_name='Navegador')),
                ('device', models.CharField(blank=True, max_length=80, verbose_name='Dispositivo')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='Ubicacion')),
                ('detail', models.CharField(blank=True, max_length=240, verbose_name='Detalle')),
            ],
            options={
                'verbose_name': 'Registro de acceso',
                'verbose_name_plural': 'Reporte de accesos',
                'db_table': 'auth_access_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('identifier', models.CharField(db_index=True, max_length=180, verbose_name='Usuario / correo')),
                ('success', models.BooleanField(default=False, verbose_name='Exitoso')),
                ('reason', models.CharField(blank=True, max_length=120, verbose_name='Motivo')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=320, verbose_name='Navegador')),
            ],
            options={
                'verbose_name': 'Intento de acceso',
                'verbose_name_plural': 'Intentos de acceso',
                'db_table': 'auth_login_attempt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=96, unique=True, verbose_name='Token')),
                ('purpose', models.CharField(choices=[('PASSWORD_RESET', 'Recuperacion de contrasena'), ('EMAIL_VERIFY', 'Verificacion de correo'), ('INVITATION', 'Invitacion de acceso')], max_length=24, verbose_name='Proposito')),
                ('expires_at', models.DateTimeField(verbose_name='Expira el')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Utilizado el')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP solicitante')),
            ],
            options={
                'verbose_name': 'Token de seguridad',
                'verbose_name_plural': 'Tokens de seguridad',
                'db_table': 'auth_security_token',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TwoFactorDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('name', models.CharField(default='Google Authenticator', max_length=80, verbose_name='Nombre del dispositivo')),
                ('secret', models.CharField(default=core.authentication.models.generate_base32_secret, max_length=64, verbose_name='Secreto')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Confirmado')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado el')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Ultimo uso')),
                ('last_counter', models.BigIntegerField(default=0, verbose_name='Ultimo contador')),
                ('recovery_codes', models.JSONField(blank=True, default=list, verbose_name='Codigos de recuperacion')),
            ],
            options={
                'verbose_name': 'Dispositivo 2FA',
                'verbose_name_plural': 'Dispositivos 2FA',
                'db_table': 'auth_two_factor_device',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('session_key', models.CharField(max_length=64, unique=True, verbose_name='Clave de sesion')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=320, verbose_name='Navegador')),
                ('last_activity', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Ultima actividad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Cerrada el')),
            ],
            options={
                'verbose_name': 'Sesion de usuario',
                'verbose_name_plural': 'Sesiones de usuario',
                'db_table': 'auth_user_session',
                'ordering': ['-last_activity'],
            },
        ),
    ]
