# Generated by Django 5.2.17 on 2026-08-23 07:09

import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClosingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('scope', models.CharField(choices=[('PERIODO', 'Cierre de periodo'), ('ANUAL', 'Cierre anual')], default='PERIODO', max_length=10, verbose_name='Alcance')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('CONSOLIDADO', 'Consolidado'), ('CERRADO', 'Cerrado'), ('REABIERTO', 'Reabierto')], default='PENDIENTE', max_length=12, verbose_name='Estado')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado el')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado el')),
                ('processed_students', models.PositiveIntegerField(default=0, verbose_name='Estudiantes procesados')),
                ('processed_grades', models.PositiveIntegerField(default=0, verbose_name='Notas consolidadas')),
                ('log', models.TextField(blank=True, verbose_name='Bitacora del proceso')),
            ],
            options={
                'verbose_name': 'Cierre academico',
                'verbose_name_plural': 'Cierres academicos',
                'db_table': 'promotion_closing',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('act_number', models.CharField(max_length=32, verbose_name='Numero de acta')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha')),
                ('place', models.CharField(blank=True, max_length=120, verbose_name='Lugar')),
                ('attendees', models.TextField(blank=True, verbose_name='Asistentes')),
                ('agenda', models.TextField(blank=True, verbose_name='Orden del dia')),
                ('decisions', models.TextField(blank=True, verbose_name='Decisiones')),
                ('commitments', models.TextField(blank=True, verbose_name='Compromisos')),
                ('closed', models.BooleanField(default=False, verbose_name='Acta cerrada')),
            ],
            options={
                'verbose_name': 'Comision de evaluacion',
                'verbose_name_plural': 'Comisiones de evaluacion',
                'db_table': 'promotion_commission',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FinalReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('is_final', models.BooleanField(default=False, verbose_name='Boletin final')),
                ('average', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Promedio')),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Puesto')),
                ('total_absences', models.PositiveSmallIntegerField(default=0, verbose_name='Total inasistencias')),
                ('tutor_observation', models.TextField(blank=True, verbose_name='Observacion del tutor')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Generado el')),
                ('published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/cards/%Y/', verbose_name='Archivo PDF')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='Detalle consolidado')),
            ],
            options={
                'verbose_name': 'Boletin',
                'verbose_name_plural': 'Boletines',
                'db_table': 'promotion_report_card',
                'ordering': ['group__grade__order', 'student__last_name'],
            },
        ),
        migrations.CreateModel(
            name='PromotionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('average', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Promedio general')),
                ('failed_subjects', models.PositiveSmallIntegerField(default=0, verbose_name='Asignaturas perdidas')),
                ('failed_areas', models.PositiveSmallIntegerField(default=0, verbose_name='Areas perdidas')),
                ('absences', models.PositiveSmallIntegerField(default=0, verbose_name='Inasistencias')),
                ('result', models.CharField(choices=[('PROMOVIDO', 'Promovido'), ('PROMOVIDO_COMPROMISO', 'Promovido con compromiso'), ('NO_PROMOVIDO', 'No promovido'), ('PENDIENTE_RECUPERACION', 'Pendiente de recuperacion'), ('GRADUADO', 'Graduado'), ('RETIRADO', 'Retirado')], db_index=True, default='PROMOVIDO', max_length=24, verbose_name='Resultado')),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Puesto en el grupo')),
                ('honor_roll', models.BooleanField(default=False, verbose_name='Cuadro de honor')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones de la comision')),
                ('approved', models.BooleanField(default=False, verbose_name='Aprobado por la comision')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprobado el')),
            ],
            options={
                'verbose_name': 'Resultado de promocion',
                'verbose_name_plural': 'Promocion estudiantil',
                'db_table': 'promotion_result',
                'ordering': ['group__grade__order', 'group__code', '-average'],
            },
        ),
    ]
