# Generated by Django 5.2.17 on 2026-08-23 07:09

import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (7, 'Domingo')], verbose_name='Dia')),
                ('block', models.PositiveSmallIntegerField(default=1, verbose_name='Bloque / hora')),
                ('start_time', models.TimeField(verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de finalizacion')),
                ('classroom', models.CharField(blank=True, max_length=40, verbose_name='Aula')),
            ],
            options={
                'verbose_name': 'Franja de horario',
                'verbose_name_plural': 'Horarios',
                'db_table': 'teacher_schedule_slot',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('teacher_code', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Codigo docente')),
                ('document_type', models.CharField(choices=[('TI', 'Tarjeta de Identidad'), ('CC', 'Cedula de Ciudadania'), ('CE', 'Cedula de Extranjeria'), ('RC', 'Registro Civil'), ('PA', 'Pasaporte'), ('NUIP', 'NUIP'), ('PEP', 'Permiso Especial de Permanencia'), ('NES', 'Numero Establecido por la Secretaria')], default='CC', max_length=8, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Numero de documento')),
                ('first_name', models.CharField(max_length=120, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=120, verbose_name='Apellidos')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'No informa')], default='N', max_length=1, verbose_name='Genero')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/photos/', verbose_name='Fotografia')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo institucional')),
                ('personal_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo personal')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Telefono')),
                ('mobile', models.CharField(blank=True, max_length=32, verbose_name='Celular')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Direccion')),
                ('profession', models.CharField(blank=True, max_length=160, verbose_name='Profesion')),
                ('academic_title', models.CharField(blank=True, max_length=160, verbose_name='Titulo academico')),
                ('specialization', models.CharField(blank=True, max_length=160, verbose_name='Especializacion')),
                ('escalafon', models.CharField(blank=True, max_length=40, verbose_name='Escalafon')),
                ('contract_type', models.CharField(choices=[('PLANTA', 'Planta'), ('PROVISIONAL', 'Provisional'), ('CONTRATO', 'Contrato'), ('CATEDRA', 'Catedra'), ('HORA_CATEDRA', 'Hora catedra')], default='CONTRATO', max_length=14, verbose_name='Tipo de vinculacion')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Fecha de vinculacion')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de retiro')),
                ('weekly_hours', models.PositiveSmallIntegerField(default=22, verbose_name='Horas semanales contratadas')),
                ('status', models.CharField(choices=[('ACTIVO', 'Activo'), ('LICENCIA', 'En licencia'), ('RETIRADO', 'Retirado'), ('INACTIVO', 'Inactivo')], db_index=True, default='ACTIVO', max_length=10, verbose_name='Estado')),
                ('is_tutor', models.BooleanField(default=False, verbose_name='Puede ser tutor')),
                ('is_coordinator', models.BooleanField(default=False, verbose_name='Es coordinador')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='teachers/signatures/', verbose_name='Firma digitalizada')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'db_table': 'teacher',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('kind', models.CharField(choices=[('INCAPACIDAD', 'Incapacidad'), ('PERMISO', 'Permiso'), ('LICENCIA', 'Licencia'), ('CAPACITACION', 'Capacitacion'), ('OTRO', 'Otro')], default='PERMISO', max_length=14, verbose_name='Tipo')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Desde')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Hasta')),
                ('reason', models.TextField(blank=True, verbose_name='Motivo')),
                ('approved', models.BooleanField(default=False, verbose_name='Aprobada')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprobada el')),
            ],
            options={
                'verbose_name': 'Novedad docente',
                'verbose_name_plural': 'Novedades docentes',
                'db_table': 'teacher_absence',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAcademicProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=160, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, verbose_name='Porcentaje (%)')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha limite')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Cerrado')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Proceso academico del docente',
                'verbose_name_plural': 'Procesos academicos del docente',
                'db_table': 'teacher_academic_process',
                'ordering': ['period__number', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('weekly_hours', models.PositiveSmallIntegerField(default=1, verbose_name='Horas semanales')),
                ('is_main', models.BooleanField(default=True, verbose_name='Docente titular')),
                ('notes', models.CharField(blank=True, max_length=240, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Asignacion academica',
                'verbose_name_plural': 'Asignaciones academicas',
                'db_table': 'teacher_assignment',
                'ordering': ['group__grade__order', 'group__code', 'subject__name'],
            },
        ),
    ]
