# Generated by Django 5.2.17 on 2026-08-23 07:09

import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoexistenceEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valoracion')),
                ('observation', models.CharField(blank=True, max_length=240, verbose_name='Observacion')),
            ],
            options={
                'verbose_name': 'Valoracion de convivencia',
                'verbose_name_plural': 'Valoraciones de convivencia',
                'db_table': 'tutoring_coexistence_evaluation',
                'ordering': ['item__order'],
            },
        ),
        migrations.CreateModel(
            name='ReportCardBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('reason', models.CharField(choices=[('CARTERA', 'Cartera pendiente'), ('DOCUMENTOS', 'Documentacion incompleta'), ('DISCIPLINA', 'Situacion disciplinaria'), ('BIBLIOTECA', 'Material pendiente'), ('OTRO', 'Otro motivo')], default='CARTERA', max_length=12, verbose_name='Motivo')),
                ('detail', models.CharField(blank=True, max_length=240, verbose_name='Detalle')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor adeudado')),
                ('blocked', models.BooleanField(default=True, verbose_name='Boletin bloqueado')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='Liberado el')),
            ],
            options={
                'verbose_name': 'Bloqueo de boletin',
                'verbose_name_plural': 'Bloqueos de boletin',
                'db_table': 'tutoring_report_block',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Desde')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Hasta')),
                ('is_main', models.BooleanField(default=True, verbose_name='Tutor principal')),
                ('notes', models.CharField(blank=True, max_length=240, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Tutor',
                'verbose_name_plural': 'Tutores',
                'db_table': 'tutoring_tutor',
                'ordering': ['group__grade__order', 'group__code'],
            },
        ),
        migrations.CreateModel(
            name='TutoringJudgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('strengths', models.TextField(blank=True, verbose_name='Fortalezas')),
                ('difficulties', models.TextField(blank=True, verbose_name='Dificultades')),
                ('recommendations', models.TextField(blank=True, verbose_name='Recomendaciones')),
                ('commitment', models.TextField(blank=True, verbose_name='Compromisos')),
                ('published', models.BooleanField(default=False, verbose_name='Publicado en el boletin')),
            ],
            options={
                'verbose_name': 'Juicio de tutoria',
                'verbose_name_plural': 'Juicios de tutoria',
                'db_table': 'tutoring_judgment',
                'ordering': ['student__last_name'],
            },
        ),
        migrations.CreateModel(
            name='TutoringMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('scheduled_at', models.DateTimeField(verbose_name='Fecha y hora')),
                ('place', models.CharField(blank=True, max_length=120, verbose_name='Lugar')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('agreements', models.TextField(blank=True, verbose_name='Acuerdos')),
                ('status', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIO', 'No asistio')], default='PROGRAMADA', max_length=12, verbose_name='Estado')),
                ('guardian_attended', models.BooleanField(default=False, verbose_name='Asistio el acudiente')),
            ],
            options={
                'verbose_name': 'Citacion de tutoria',
                'verbose_name_plural': 'Citaciones de tutoria',
                'db_table': 'tutoring_meeting',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
