# Generated by Django 5.2.17 on 2026-08-23 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('students', '0002_initial'),
        ('teachers', '0002_initial'),
        ('tutoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coexistenceevaluation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='coexistenceevaluation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AddField(
            model_name='coexistenceevaluation',
            name='evaluated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coexistence_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Evaluado por'),
        ),
        migrations.AddField(
            model_name='coexistenceevaluation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='academic.coexistenceitem', verbose_name='Item de convivencia'),
        ),
        migrations.AddField(
            model_name='coexistenceevaluation',
            name='performance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coexistence_evaluations', to='academic.gradingscalelevel', verbose_name='Desempeno'),
        ),
        migrations.AddField(
            model_name='coexistenceevaluation',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coexistence_evaluations', to='academic.academicperiod', verbose_name='Periodo'),
        ),
        migrations.AddField(
            model_name='coexistenceevaluation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coexistence_evaluations', to='students.student', verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='coexistenceevaluation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='reportcardblock',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='reportcardblock',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AddField(
            model_name='reportcardblock',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_blocks', to='academic.academicperiod', verbose_name='Periodo'),
        ),
        migrations.AddField(
            model_name='reportcardblock',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_report_blocks', to=settings.AUTH_USER_MODEL, verbose_name='Liberado por'),
        ),
        migrations.AddField(
            model_name='reportcardblock',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_blocks', to='academic.schoolyear', verbose_name='Ano lectivo'),
        ),
        migrations.AddField(
            model_name='reportcardblock',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_blocks', to='students.student', verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='reportcardblock',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to='academic.group', verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to='academic.schoolyear', verbose_name='Ano lectivo'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorships', to='teachers.teacher', verbose_name='Docente tutor'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='tutoringjudgment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='tutoringjudgment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AddField(
            model_name='tutoringjudgment',
            name='performance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutoring_judgments', to='academic.gradingscalelevel', verbose_name='Desempeno global'),
        ),
        migrations.AddField(
            model_name='tutoringjudgment',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_judgments', to='academic.academicperiod', verbose_name='Periodo'),
        ),
        migrations.AddField(
            model_name='tutoringjudgment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_judgments', to='students.student', verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='tutoringjudgment',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judgments', to='tutoring.tutor', verbose_name='Tutor'),
        ),
        migrations.AddField(
            model_name='tutoringjudgment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='tutoringmeeting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='tutoringmeeting',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AddField(
            model_name='tutoringmeeting',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_meetings', to='students.student', verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='tutoringmeeting',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='tutoring.tutor', verbose_name='Tutor'),
        ),
        migrations.AddField(
            model_name='tutoringmeeting',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AlterUniqueTogether(
            name='coexistenceevaluation',
            unique_together={('student', 'period', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='tutor',
            unique_together={('school_year', 'group', 'teacher')},
        ),
        migrations.AlterUniqueTogether(
            name='tutoringjudgment',
            unique_together={('student', 'period')},
        ),
    ]
