# Generated by Django 5.2.17 on 2026-08-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('user_label', models.CharField(blank=True, max_length=180, verbose_name='Usuario (texto)')),
                ('role_label', models.CharField(blank=True, max_length=80, verbose_name='Perfil')),
                ('action', models.CharField(choices=[('CREATE', 'Creacion'), ('UPDATE', 'Modificacion'), ('DELETE', 'Eliminacion'), ('VIEW', 'Consulta'), ('EXPORT', 'Exportacion'), ('APPROVE', 'Aprobacion'), ('TOGGLE', 'Cambio de estado'), ('LOGIN', 'Inicio de sesion'), ('LOGOUT', 'Cierre de sesion'), ('ERROR', 'Error'), ('PROCESS', 'Proceso academico')], db_index=True, max_length=20, verbose_name='Accion')),
                ('module', models.CharField(db_index=True, max_length=80, verbose_name='Modulo')),
                ('model_name', models.CharField(blank=True, max_length=120, verbose_name='Entidad')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='Identificador')),
                ('object_label', models.CharField(blank=True, max_length=240, verbose_name='Registro')),
                ('description', models.CharField(blank=True, max_length=320, verbose_name='Descripcion')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Cambios')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=320, verbose_name='Navegador')),
                ('path', models.CharField(blank=True, max_length=320, verbose_name='Ruta')),
                ('method', models.CharField(blank=True, max_length=10, verbose_name='Metodo')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Codigo HTTP')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duracion (ms)')),
            ],
            options={
                'verbose_name': 'Registro de auditoria',
                'verbose_name_plural': 'Bitacora de auditoria',
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
