# Generated by Django 5.2.17 on 2026-08-23 07:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilingualEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('listening', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Listening')),
                ('speaking', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Speaking')),
                ('reading', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Reading')),
                ('writing', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Writing')),
                ('grammar', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Grammar')),
                ('average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Promedio')),
                ('cefr_level', models.CharField(blank=True, choices=[('A1', 'A1 - Principiante'), ('A2', 'A2 - Basico'), ('B1', 'B1 - Intermedio'), ('B2', 'B2 - Intermedio alto'), ('C1', 'C1 - Avanzado'), ('C2', 'C2 - Maestria')], max_length=2, verbose_name='Nivel MCER')),
                ('comments', models.TextField(blank=True, verbose_name='Comentarios')),
            ],
            options={
                'verbose_name': 'Evaluacion bilingue',
                'verbose_name_plural': 'Modulo bilingue',
                'db_table': 'evaluation_bilingual',
                'ordering': ['student__last_name'],
            },
        ),
        migrations.CreateModel(
            name='GradeSheetLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('locked', models.BooleanField(default=True, verbose_name='Bloqueado')),
                ('reason', models.CharField(blank=True, max_length=240, verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'Bloqueo de digitacion',
                'verbose_name_plural': 'Bloqueos de digitacion',
                'db_table': 'evaluation_grade_lock',
            },
        ),
        migrations.CreateModel(
            name='ProcessGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota')),
                ('observation', models.CharField(blank=True, max_length=240, verbose_name='Observacion')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registrada el')),
            ],
            options={
                'verbose_name': 'Nota de proceso',
                'verbose_name_plural': 'Notas de procesos',
                'db_table': 'evaluation_process_grade',
                'ordering': ['student__last_name', 'process__order'],
            },
        ),
        migrations.CreateModel(
            name='PurposeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('achievement', models.CharField(choices=[('SUPERADO', 'Superado'), ('EN_PROCESO', 'En proceso'), ('INICIADO', 'Iniciado'), ('NO_LOGRADO', 'No logrado')], default='EN_PROCESO', max_length=12, verbose_name='Nivel de logro')),
                ('observation', models.TextField(blank=True, verbose_name='Observacion')),
            ],
            options={
                'verbose_name': 'Valoracion de proposito',
                'verbose_name_plural': 'Propositos preescolar',
                'db_table': 'evaluation_purpose',
                'ordering': ['purpose__order'],
            },
        ),
        migrations.CreateModel(
            name='QualitativeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('description', models.TextField(blank=True, verbose_name='Valoracion cualitativa')),
                ('strengths', models.TextField(blank=True, verbose_name='Fortalezas')),
                ('difficulties', models.TextField(blank=True, verbose_name='Dificultades')),
                ('recommendations', models.TextField(blank=True, verbose_name='Recomendaciones')),
            ],
            options={
                'verbose_name': 'Evaluacion cualitativa',
                'verbose_name_plural': 'Evaluaciones cualitativas',
                'db_table': 'evaluation_qualitative',
                'ordering': ['student__last_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentJudgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('custom_text', models.TextField(blank=True, verbose_name='Texto personalizado')),
                ('judgment_type', models.CharField(default='DESEMPENO', max_length=16, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Juicio valorativo del estudiante',
                'verbose_name_plural': 'Juicios valorativos de estudiantes',
                'db_table': 'evaluation_student_judgment',
                'ordering': ['subject__order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubjectGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota del periodo')),
                ('recovered_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota de recuperacion')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota definitiva')),
                ('absences', models.PositiveSmallIntegerField(default=0, verbose_name='Fallas')),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADA', 'Publicada'), ('CERRADA', 'Cerrada'), ('RECUPERADA', 'Recuperada')], default='BORRADOR', max_length=12, verbose_name='Estado')),
                ('is_passing', models.BooleanField(default=True, verbose_name='Aprobada')),
                ('observation', models.TextField(blank=True, verbose_name='Observacion')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicada el')),
            ],
            options={
                'verbose_name': 'Nota de asignatura',
                'verbose_name_plural': 'Notas de asignaturas',
                'db_table': 'evaluation_subject_grade',
                'ordering': ['subject__area__order', 'subject__order'],
            },
        ),
        migrations.CreateModel(
            name='AreaGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota del area')),
                ('is_passing', models.BooleanField(default=True, verbose_name='Aprobada')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academic.area', verbose_name='Area')),
            ],
            options={
                'verbose_name': 'Nota de area',
                'verbose_name_plural': 'Notas de areas',
                'db_table': 'evaluation_area_grade',
                'ordering': ['area__order'],
            },
        ),
    ]
