# Generated by Django 5.2.17 on 2026-08-23 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('evaluations', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='areagrade',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='areagrade',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AddField(
            model_name='areagrade',
            name='performance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_grades', to='academic.gradingscalelevel', verbose_name='Desempeno'),
        ),
        migrations.AddField(
            model_name='areagrade',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_grades', to='academic.academicperiod', verbose_name='Periodo'),
        ),
        migrations.AddField(
            model_name='areagrade',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_grades', to='academic.schoolyear', verbose_name='Ano lectivo'),
        ),
        migrations.AddField(
            model_name='areagrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_grades', to='students.student', verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='areagrade',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='bilingualevaluation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='bilingualevaluation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AddField(
            model_name='bilingualevaluation',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilingual_evaluations', to='academic.academicperiod', verbose_name='Periodo'),
        ),
        migrations.AddField(
            model_name='bilingualevaluation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilingual_evaluations', to='students.student', verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='bilingualevaluation',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilingual_evaluations', to='academic.subject', verbose_name='Asignatura bilingue'),
        ),
        migrations.AddField(
            model_name='bilingualevaluation',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bilingual_evaluations', to='teachers.teacher', verbose_name='Docente'),
        ),
        migrations.AddField(
            model_name='bilingualevaluation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='gradesheetlock',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='gradesheetlock',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AddField(
            model_name='gradesheetlock',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_locks', to='academic.group', verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='gradesheetlock',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_locks', to=settings.AUTH_USER_MODEL, verbose_name='Bloqueado por'),
        ),
        migrations.AddField(
            model_name='gradesheetlock',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_locks', to='academic.academicperiod', verbose_name='Periodo'),
        ),
        migrations.AddField(
            model_name='gradesheetlock',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_locks', to='academic.subject', verbose_name='Asignatura'),
        ),
        migrations.AddField(
            model_name='gradesheetlock',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='processgrade',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_grades', to='teachers.teachingassignment', verbose_name='Asignacion'),
        ),
        migrations.AddField(
            model_name='processgrade',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='processgrade',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AddField(
            model_name='processgrade',
            name='dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_grades', to='academic.valuationdimension', verbose_name='Dimension'),
        ),
        migrations.AddField(
            model_name='processgrade',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_grades', to='academic.academicperiod', verbose_name='Periodo'),
        ),
        migrations.AddField(
            model_name='processgrade',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='teachers.teacheracademicprocess', verbose_name='Proceso'),
        ),
        migrations.AddField(
            model_name='processgrade',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_grades', to=settings.AUTH_USER_MODEL, verbose_name='Registrada por'),
        ),
        migrations.AddField(
            model_name='processgrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_grades', to='students.student', verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='processgrade',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='purposeevaluation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='purposeevaluation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AddField(
            model_name='purposeevaluation',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purpose_evaluations', to='academic.academicperiod', verbose_name='Periodo'),
        ),
        migrations.AddField(
            model_name='purposeevaluation',
            name='purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='academic.purpose', verbose_name='Proposito'),
        ),
        migrations.AddField(
            model_name='purposeevaluation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purpose_evaluations', to='students.student', verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='purposeevaluation',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purpose_evaluations', to='teachers.teacher', verbose_name='Docente'),
        ),
        migrations.AddField(
            model_name='purposeevaluation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='qualitativeevaluation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='qualitativeevaluation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AddField(
            model_name='qualitativeevaluation',
            name='dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualitative_evaluations', to='academic.valuationdimension', verbose_name='Dimension'),
        ),
        migrations.AddField(
            model_name='qualitativeevaluation',
            name='performance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualitative_evaluations', to='academic.gradingscalelevel', verbose_name='Desempeno'),
        ),
        migrations.AddField(
            model_name='qualitativeevaluation',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualitative_evaluations', to='academic.academicperiod', verbose_name='Periodo'),
        ),
        migrations.AddField(
            model_name='qualitativeevaluation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualitative_evaluations', to='students.student', verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='qualitativeevaluation',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualitative_evaluations', to='academic.subject', verbose_name='Asignatura'),
        ),
        migrations.AddField(
            model_name='qualitativeevaluation',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualitative_evaluations', to='teachers.teacher', verbose_name='Docente'),
        ),
        migrations.AddField(
            model_name='qualitativeevaluation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='studentjudgment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='studentjudgment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AddField(
            model_name='studentjudgment',
            name='judgment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='academic.valuejudgment', verbose_name='Juicio'),
        ),
        migrations.AddField(
            model_name='studentjudgment',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_judgments', to='academic.academicperiod', verbose_name='Periodo'),
        ),
        migrations.AddField(
            model_name='studentjudgment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judgments', to='students.student', verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='studentjudgment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_judgments', to='academic.subject', verbose_name='Asignatura'),
        ),
        migrations.AddField(
            model_name='studentjudgment',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_judgments', to='teachers.teacher', verbose_name='Docente'),
        ),
        migrations.AddField(
            model_name='studentjudgment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to='students.enrollment', verbose_name='Matricula'),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to='academic.group', verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='performance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_grades', to='academic.gradingscalelevel', verbose_name='Desempeno'),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to='academic.academicperiod', verbose_name='Periodo'),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to='academic.schoolyear', verbose_name='Ano lectivo'),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to='students.student', verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to='academic.subject', verbose_name='Asignatura'),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_grades', to='teachers.teacher', verbose_name='Docente'),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AlterUniqueTogether(
            name='areagrade',
            unique_together={('student', 'period', 'area')},
        ),
        migrations.AlterUniqueTogether(
            name='bilingualevaluation',
            unique_together={('student', 'period', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='gradesheetlock',
            unique_together={('period', 'group', 'subject')},
        ),
        migrations.AddIndex(
            model_name='processgrade',
            index=models.Index(fields=['period', 'assignment'], name='evaluation__period__dea047_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='processgrade',
            unique_together={('student', 'process')},
        ),
        migrations.AlterUniqueTogether(
            name='purposeevaluation',
            unique_together={('student', 'purpose', 'period')},
        ),
        migrations.AddIndex(
            model_name='subjectgrade',
            index=models.Index(fields=['school_year', 'period', 'group'], name='evaluation__school__dcd5e7_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectgrade',
            index=models.Index(fields=['student', 'period'], name='evaluation__student_1036cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectgrade',
            unique_together={('student', 'period', 'subject')},
        ),
    ]
