# Generated by Django 5.2.17 on 2026-08-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradesheetlock',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bloqueo de digitacion', 'verbose_name_plural': 'Bloqueos de digitacion'},
        ),
    ]
