# Generated by Django 5.2.17 on 2026-08-23 07:09

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('assigned_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de asignacion')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('status', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_CURSO', 'En curso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=12, verbose_name='Estado')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='agenda/activities/%Y/%m/', verbose_name='Material')),
                ('notify_guardians', models.BooleanField(default=True, verbose_name='Notificar acudientes')),
            ],
            options={
                'verbose_name': 'Actividad de agenda',
                'verbose_name_plural': 'Actividades de agenda',
                'db_table': 'agenda_activity',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='AgendaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('event_type', models.CharField(choices=[('ACADEMICO', 'Academico'), ('INSTITUCIONAL', 'Institucional'), ('CULTURAL', 'Cultural'), ('DEPORTIVO', 'Deportivo'), ('REUNION', 'Reunion'), ('EVALUACION', 'Evaluacion'), ('FESTIVO', 'Festivo'), ('ENTREGA_BOLETINES', 'Entrega de boletines')], default='ACADEMICO', max_length=20, verbose_name='Tipo')),
                ('audience', models.CharField(choices=[('TODOS', 'Toda la comunidad'), ('ESTUDIANTES', 'Estudiantes'), ('DOCENTES', 'Docentes'), ('ACUDIENTES', 'Acudientes'), ('DIRECTIVOS', 'Directivos'), ('GRUPO', 'Grupo especifico')], default='TODOS', max_length=12, verbose_name='Dirigido a')),
                ('start_at', models.DateTimeField(db_index=True, verbose_name='Inicio')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('all_day', models.BooleanField(default=False, verbose_name='Todo el dia')),
                ('place', models.CharField(blank=True, max_length=160, verbose_name='Lugar')),
                ('color', models.CharField(default='#4F46E5', max_length=20, verbose_name='Color')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('send_notification', models.BooleanField(default=False, verbose_name='Notificar')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='agenda/%Y/%m/', verbose_name='Anexo')),
            ],
            options={
                'verbose_name': 'Evento de agenda',
                'verbose_name_plural': 'Agenda institucional',
                'db_table': 'agenda_event',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('number', models.CharField(blank=True, max_length=24, verbose_name='Numero')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('body', models.TextField(verbose_name='Contenido')),
                ('audience', models.CharField(choices=[('TODOS', 'Toda la comunidad'), ('ESTUDIANTES', 'Estudiantes'), ('DOCENTES', 'Docentes'), ('ACUDIENTES', 'Acudientes'), ('GRUPO', 'Grupos seleccionados')], default='TODOS', max_length=12, verbose_name='Dirigido a')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='agenda/circulars/%Y/%m/', verbose_name='Anexo')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Programada para')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviada el')),
                ('recipients_count', models.PositiveIntegerField(default=0, verbose_name='Destinatarios')),
                ('opened_count', models.PositiveIntegerField(default=0, verbose_name='Aperturas')),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PROGRAMADA', 'Programada'), ('ENVIADA', 'Enviada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=12, verbose_name='Estado')),
                ('send_email', models.BooleanField(default=True, verbose_name='Enviar por correo')),
            ],
            options={
                'verbose_name': 'Circular',
                'verbose_name_plural': 'Circulares',
                'db_table': 'agenda_circular',
                'ordering': ['-created_at'],
            },
        ),
    ]
