# Generated by Django 5.2.17 on 2026-08-23 07:09

import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('content', models.TextField(blank=True, verbose_name='Respuesta')),
                ('file', models.FileField(blank=True, null=True, upload_to='classroom/submissions/%Y/%m/', verbose_name='Archivo')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregada el')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADA', 'Entregada'), ('TARDE', 'Entregada tarde'), ('CALIFICADA', 'Calificada'), ('NO_ENTREGADA', 'No entregada')], default='PENDIENTE', max_length=14, verbose_name='Estado')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota')),
                ('feedback', models.TextField(blank=True, verbose_name='Retroalimentacion')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Calificada el')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'db_table': 'classroom_submission',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo del curso')),
                ('summary', models.TextField(blank=True, verbose_name='Descripcion')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='classroom/covers/', verbose_name='Portada')),
                ('color', models.CharField(default='#6366F1', max_length=20, verbose_name='Color')),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', max_length=10, verbose_name='Estado')),
                ('allow_submissions', models.BooleanField(default=True, verbose_name='Permite entregas')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'classroom_course',
                'ordering': ['group__grade__order', 'subject__name'],
            },
        ),
        migrations.CreateModel(
            name='CourseActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('instructions', models.TextField(blank=True, verbose_name='Instrucciones')),
                ('kind', models.CharField(choices=[('TAREA', 'Tarea'), ('TALLER', 'Taller'), ('QUIZ', 'Quiz'), ('PROYECTO', 'Proyecto'), ('FORO', 'Foro'), ('EXPOSICION', 'Exposicion')], default='TAREA', max_length=12, verbose_name='Tipo')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='classroom/activities/%Y/%m/', verbose_name='Material anexo')),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='Nota maxima')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, verbose_name='Porcentaje (%)')),
                ('opens_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Disponible desde')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='Entrega hasta')),
                ('allow_late', models.BooleanField(default=False, verbose_name='Permite entrega tardia')),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADA', 'Publicada'), ('CERRADA', 'Cerrada'), ('CALIFICADA', 'Calificada')], default='BORRADOR', max_length=12, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Actividad del aula',
                'verbose_name_plural': 'Actividades del aula',
                'db_table': 'classroom_activity',
                'ordering': ['-opens_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('kind', models.CharField(choices=[('DOCUMENTO', 'Documento'), ('PRESENTACION', 'Presentacion'), ('VIDEO', 'Video'), ('ENLACE', 'Enlace externo'), ('GUIA', 'Guia de trabajo'), ('LECTURA', 'Lectura')], default='DOCUMENTO', max_length=14, verbose_name='Tipo')),
                ('file', models.FileField(blank=True, null=True, upload_to='classroom/materials/%Y/%m/', verbose_name='Archivo')),
                ('url', models.URLField(blank=True, verbose_name='Enlace')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publicado el')),
                ('downloads', models.PositiveIntegerField(default=0, verbose_name='Descargas')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Material academico',
                'verbose_name_plural': 'Materiales academicos',
                'db_table': 'classroom_material',
                'ordering': ['order', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('activities_total', models.PositiveSmallIntegerField(default=0, verbose_name='Actividades totales')),
                ('activities_done', models.PositiveSmallIntegerField(default=0, verbose_name='Actividades entregadas')),
                ('average_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Promedio')),
                ('last_access', models.DateTimeField(blank=True, null=True, verbose_name='Ultimo acceso')),
            ],
            options={
                'verbose_name': 'Progreso del curso',
                'verbose_name_plural': 'Seguimiento del aula virtual',
                'db_table': 'classroom_progress',
            },
        ),
        migrations.CreateModel(
            name='CourseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('title', models.CharField(max_length=180, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicada')),
            ],
            options={
                'verbose_name': 'Unidad del curso',
                'verbose_name_plural': 'Unidades del curso',
                'db_table': 'classroom_unit',
                'ordering': ['order', 'id'],
            },
        ),
    ]
