# Generated by Django 5.2.17 on 2026-08-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseprogress',
            options={'ordering': ['student__last_name'], 'verbose_name': 'Progreso del curso', 'verbose_name_plural': 'Seguimiento del aula virtual'},
        ),
    ]
