-- ============================================================================
--  PL_SGE - Extension nativa: INCAPACIDADES y CONVIVENCIA ESCOLAR
--  10 - MIGRACION (CREATE TABLE, FOREIGN KEYS, INDICES, CONSTRAINTS)
-- ----------------------------------------------------------------------------
--  Motor        : PostgreSQL 14 o superior
--  Codificacion : UTF8
--  Ejecutar sobre la base pl_sge ya instalada.
--
--  IMPORTANTE
--  Este script es ADITIVO. No modifica ni elimina ninguna tabla, columna ni
--  restriccion existente. Es reversible con 11_rollback.sql.
--
--  Requiere las tablas productivas: users_user, student, teacher,
--  student_guardian, student_document, teacher_absence, attendance_record,
--  academic_school_year, institution_campus, observer_entry.
-- ============================================================================

BEGIN;

SET client_encoding = 'UTF8';
SET client_min_messages = warning;

-- ----------------------------------------------------------------------------
-- Verificacion previa: no continuar si el sistema base no esta instalado.
-- ----------------------------------------------------------------------------
DO $$
DECLARE
    faltantes text;
BEGIN
    SELECT string_agg(t, ', ') INTO faltantes
    FROM (VALUES ('users_user'), ('student'), ('teacher'), ('student_guardian'),
                 ('student_document'), ('teacher_absence'), ('attendance_record'),
                 ('academic_school_year'), ('institution_campus'), ('observer_entry')) AS v(t)
    WHERE to_regclass('public.' || t) IS NULL;

    IF faltantes IS NOT NULL THEN
        RAISE EXCEPTION 'Faltan tablas del sistema base: %. Instale PL_SGE antes de aplicar la extension.', faltantes;
    END IF;
END $$;


-- ============================================================================
--  MODULO 1 - INCAPACIDADES
-- ============================================================================

-- ---------------------------------------------------------------- 1.1 Tipos
CREATE TABLE public.incapacity_type (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at            timestamp with time zone NOT NULL DEFAULT now(),
    updated_at            timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at            timestamp with time zone,
    uuid                  uuid NOT NULL DEFAULT gen_random_uuid(),
    is_active             boolean NOT NULL DEFAULT true,
    code                  character varying(32)  NOT NULL,
    name                  character varying(180) NOT NULL,
    description           text NOT NULL DEFAULT '',
    "order"               smallint NOT NULL DEFAULT 0,
    applies_to            character varying(16)  NOT NULL DEFAULT 'TODOS',
    requires_support      boolean NOT NULL DEFAULT true,
    requires_diagnosis    boolean NOT NULL DEFAULT false,
    justifies_attendance  boolean NOT NULL DEFAULT true,
    max_days              smallint,
    color                 character varying(20)  NOT NULL DEFAULT '#0EA5E9',
    created_by_id         bigint,
    updated_by_id         bigint,
    deleted_by_id         bigint,
    CONSTRAINT uq_incapacity_type_code   UNIQUE (code),
    CONSTRAINT uq_incapacity_type_uuid   UNIQUE (uuid),
    CONSTRAINT ck_incapacity_type_scope  CHECK (applies_to IN ('ESTUDIANTE','DOCENTE','ADMINISTRATIVO','TODOS')),
    CONSTRAINT ck_incapacity_type_maxdays CHECK (max_days IS NULL OR max_days > 0)
);

-- --------------------------------------------------------- 1.2 Incapacidad
CREATE TABLE public.incapacity (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at              timestamp with time zone NOT NULL DEFAULT now(),
    updated_at              timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at              timestamp with time zone,
    uuid                    uuid NOT NULL DEFAULT gen_random_uuid(),
    is_active               boolean NOT NULL DEFAULT true,

    number                  character varying(32)  NOT NULL,
    subject_type            character varying(16)  NOT NULL,
    student_id              bigint,
    teacher_id              bigint,
    subject_user_id         bigint,

    incapacity_type_id      bigint NOT NULL,
    school_year_id          bigint NOT NULL,
    campus_id               bigint,

    start_date              date NOT NULL,
    end_date                date NOT NULL,
    days                    smallint NOT NULL DEFAULT 1,
    working_days            smallint NOT NULL DEFAULT 0,

    issuer                  character varying(180) NOT NULL DEFAULT '',
    folio                   character varying(60)  NOT NULL DEFAULT '',
    diagnosis               character varying(240) NOT NULL DEFAULT '',
    cie10_code              character varying(10)  NOT NULL DEFAULT '',

    is_extension            boolean NOT NULL DEFAULT false,
    parent_id               bigint,

    status                  character varying(12)  NOT NULL DEFAULT 'PENDIENTE',
    support_verified        boolean NOT NULL DEFAULT false,
    verified_by_id          bigint,
    verified_at             timestamp with time zone,
    approved_by_id          bigint,
    approved_at             timestamp with time zone,
    rejection_reason        text NOT NULL DEFAULT '',
    cancellation_reason     text NOT NULL DEFAULT '',

    attendance_applied      boolean NOT NULL DEFAULT false,
    attendance_applied_at   timestamp with time zone,
    teacher_absence_id      bigint,
    student_document_id     bigint,

    reported_by_id          bigint,
    observations            text NOT NULL DEFAULT '',
    created_by_id           bigint,
    updated_by_id           bigint,
    deleted_by_id           bigint,

    CONSTRAINT uq_incapacity_number  UNIQUE (number),
    CONSTRAINT uq_incapacity_uuid    UNIQUE (uuid),
    CONSTRAINT uq_incapacity_absence UNIQUE (teacher_absence_id),

    CONSTRAINT ck_incapacity_status CHECK (
        status IN ('PENDIENTE','EN_REVISION','APROBADA','RECHAZADA','ANULADA')),
    CONSTRAINT ck_incapacity_dates  CHECK (end_date >= start_date),
    CONSTRAINT ck_incapacity_days   CHECK (days >= 1),

    -- RN: exactamente un sujeto, con integridad referencial real.
    CONSTRAINT ck_incapacity_subject CHECK (
        (subject_type = 'ESTUDIANTE'     AND student_id      IS NOT NULL AND teacher_id IS NULL     AND subject_user_id IS NULL) OR
        (subject_type = 'DOCENTE'        AND teacher_id      IS NOT NULL AND student_id IS NULL     AND subject_user_id IS NULL) OR
        (subject_type = 'ADMINISTRATIVO' AND subject_user_id IS NOT NULL AND student_id IS NULL     AND teacher_id      IS NULL)
    )
);

-- ------------------------------------------------------------ 1.3 Soportes
CREATE TABLE public.incapacity_attachment (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       timestamp with time zone NOT NULL DEFAULT now(),
    updated_at       timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at       timestamp with time zone,
    uuid             uuid NOT NULL DEFAULT gen_random_uuid(),
    is_active        boolean NOT NULL DEFAULT true,
    incapacity_id    bigint NOT NULL,
    name             character varying(200) NOT NULL,
    file             character varying(100) NOT NULL,
    kind             character varying(20)  NOT NULL DEFAULT 'CERTIFICADO',
    file_size        integer NOT NULL DEFAULT 0,
    content_type     character varying(120) NOT NULL DEFAULT '',
    is_confidential  boolean NOT NULL DEFAULT true,
    uploaded_at      timestamp with time zone NOT NULL DEFAULT now(),
    downloads        integer NOT NULL DEFAULT 0,
    created_by_id    bigint,
    updated_by_id    bigint,
    deleted_by_id    bigint,
    CONSTRAINT uq_incapacity_attachment_uuid UNIQUE (uuid),
    CONSTRAINT ck_incapacity_attachment_kind CHECK (
        kind IN ('CERTIFICADO','EPICRISIS','ORDEN','FORMULA','OTRO')),
    CONSTRAINT ck_incapacity_attachment_size CHECK (file_size >= 0)
);

-- ------------------------------------------------------------ 1.4 Historial
CREATE TABLE public.incapacity_history (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       timestamp with time zone NOT NULL DEFAULT now(),
    updated_at       timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at       timestamp with time zone,
    uuid             uuid NOT NULL DEFAULT gen_random_uuid(),
    is_active        boolean NOT NULL DEFAULT true,
    incapacity_id    bigint NOT NULL,
    previous_status  character varying(12) NOT NULL DEFAULT '',
    new_status       character varying(12) NOT NULL,
    reason           text NOT NULL DEFAULT '',
    changed_at       timestamp with time zone NOT NULL DEFAULT now(),
    changed_by_id    bigint,
    created_by_id    bigint,
    updated_by_id    bigint,
    deleted_by_id    bigint,
    CONSTRAINT uq_incapacity_history_uuid UNIQUE (uuid)
);

-- ------------------------------- 1.5 Vinculo con asistencia (reversibilidad)
CREATE TABLE public.incapacity_attendance_link (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at            timestamp with time zone NOT NULL DEFAULT now(),
    updated_at            timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at            timestamp with time zone,
    uuid                  uuid NOT NULL DEFAULT gen_random_uuid(),
    is_active             boolean NOT NULL DEFAULT true,
    incapacity_id         bigint NOT NULL,
    attendance_record_id  bigint NOT NULL,
    previous_status       character varying(10) NOT NULL,
    applied_at            timestamp with time zone NOT NULL DEFAULT now(),
    reverted_at           timestamp with time zone,
    created_by_id         bigint,
    updated_by_id         bigint,
    deleted_by_id         bigint,
    CONSTRAINT uq_incapacity_link      UNIQUE (incapacity_id, attendance_record_id),
    CONSTRAINT uq_incapacity_link_uuid UNIQUE (uuid)
);


-- ============================================================================
--  MODULO 2 - CONVIVENCIA ESCOLAR (extension de observer)
-- ============================================================================

-- ----------------------------------------------------------- 2.1 Evidencias
CREATE TABLE public.observer_evidence (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       timestamp with time zone NOT NULL DEFAULT now(),
    updated_at       timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at       timestamp with time zone,
    uuid             uuid NOT NULL DEFAULT gen_random_uuid(),
    is_active        boolean NOT NULL DEFAULT true,
    entry_id         bigint NOT NULL,
    kind             character varying(16)  NOT NULL DEFAULT 'DOCUMENTO',
    name             character varying(200) NOT NULL,
    description      text NOT NULL DEFAULT '',
    file             character varying(100) NOT NULL,
    file_size        integer NOT NULL DEFAULT 0,
    content_type     character varying(120) NOT NULL DEFAULT '',
    captured_at      timestamp with time zone NOT NULL DEFAULT now(),
    is_confidential  boolean NOT NULL DEFAULT false,
    created_by_id    bigint,
    updated_by_id    bigint,
    deleted_by_id    bigint,
    CONSTRAINT uq_observer_evidence_uuid UNIQUE (uuid),
    CONSTRAINT ck_observer_evidence_kind CHECK (
        kind IN ('FOTOGRAFIA','DOCUMENTO','ACTA','TESTIMONIO','AUDIO','VIDEO','OTRO'))
);

-- ----------------------------------------------------------- 2.2 Citaciones
CREATE TABLE public.observer_summons (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at           timestamp with time zone NOT NULL DEFAULT now(),
    updated_at           timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at           timestamp with time zone,
    uuid                 uuid NOT NULL DEFAULT gen_random_uuid(),
    is_active            boolean NOT NULL DEFAULT true,
    entry_id             bigint NOT NULL,
    guardian_id          bigint,
    number               character varying(32) NOT NULL,
    scheduled_at         timestamp with time zone NOT NULL,
    place                character varying(160) NOT NULL DEFAULT '',
    channel              character varying(12)  NOT NULL DEFAULT 'PRESENCIAL',
    reason               text NOT NULL,
    status               character varying(14)  NOT NULL DEFAULT 'PROGRAMADA',
    attended_at          timestamp with time zone,
    attendees            text NOT NULL DEFAULT '',
    notes                text NOT NULL DEFAULT '',
    guardian_signed      boolean NOT NULL DEFAULT false,
    student_signed       boolean NOT NULL DEFAULT false,
    rescheduled_from_id  bigint,
    notified_at          timestamp with time zone,
    created_by_id        bigint,
    updated_by_id        bigint,
    deleted_by_id        bigint,
    CONSTRAINT uq_observer_summons_number UNIQUE (number),
    CONSTRAINT uq_observer_summons_uuid   UNIQUE (uuid),
    CONSTRAINT ck_observer_summons_status CHECK (
        status IN ('PROGRAMADA','ATENDIDA','NO_ASISTIO','REPROGRAMADA','CANCELADA')),
    CONSTRAINT ck_observer_summons_channel CHECK (
        channel IN ('PRESENCIAL','VIRTUAL','TELEFONICA','CORREO'))
);

-- --------------------------------------------------------- 2.3 Compromisos
CREATE TABLE public.observer_commitment (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at           timestamp with time zone NOT NULL DEFAULT now(),
    updated_at           timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at           timestamp with time zone,
    uuid                 uuid NOT NULL DEFAULT gen_random_uuid(),
    is_active            boolean NOT NULL DEFAULT true,
    entry_id             bigint NOT NULL,
    summons_id           bigint,
    description          text NOT NULL,
    responsible_kind     character varying(14)  NOT NULL DEFAULT 'ESTUDIANTE',
    responsible_name     character varying(180) NOT NULL DEFAULT '',
    responsible_user_id  bigint,
    indicator            character varying(200) NOT NULL DEFAULT '',
    start_date           date NOT NULL DEFAULT CURRENT_DATE,
    due_date             date NOT NULL,
    status               character varying(12)  NOT NULL DEFAULT 'VIGENTE',
    verified_at          timestamp with time zone,
    verified_by_id       bigint,
    verification_note    text NOT NULL DEFAULT '',
    created_by_id        bigint,
    updated_by_id        bigint,
    deleted_by_id        bigint,
    CONSTRAINT uq_observer_commitment_uuid UNIQUE (uuid),
    CONSTRAINT ck_observer_commitment_status CHECK (
        status IN ('VIGENTE','CUMPLIDO','INCUMPLIDO','ANULADO')),
    CONSTRAINT ck_observer_commitment_kind CHECK (
        responsible_kind IN ('ESTUDIANTE','ACUDIENTE','INSTITUCION','DOCENTE')),
    CONSTRAINT ck_observer_commitment_dates CHECK (due_date >= start_date)
);

-- -------------------------------------------------------------- 2.4 Comite
CREATE TABLE public.observer_committee (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at         timestamp with time zone NOT NULL DEFAULT now(),
    updated_at         timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at         timestamp with time zone,
    uuid               uuid NOT NULL DEFAULT gen_random_uuid(),
    is_active          boolean NOT NULL DEFAULT true,
    school_year_id     bigint NOT NULL,
    campus_id          bigint,
    name               character varying(180) NOT NULL,
    constitution_act   character varying(60)  NOT NULL DEFAULT '',
    constituted_on     date,
    quorum_minimum     smallint NOT NULL DEFAULT 3,
    status             character varying(12)  NOT NULL DEFAULT 'VIGENTE',
    observations       text NOT NULL DEFAULT '',
    created_by_id      bigint,
    updated_by_id      bigint,
    deleted_by_id      bigint,
    CONSTRAINT uq_observer_committee_uuid UNIQUE (uuid),
    CONSTRAINT ck_observer_committee_status CHECK (status IN ('VIGENTE','DISUELTO')),
    CONSTRAINT ck_observer_committee_quorum CHECK (quorum_minimum >= 1)
);

-- ------------------------------------------------------------ 2.5 Miembros
CREATE TABLE public.observer_committee_member (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     timestamp with time zone NOT NULL DEFAULT now(),
    updated_at     timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at     timestamp with time zone,
    uuid           uuid NOT NULL DEFAULT gen_random_uuid(),
    is_active      boolean NOT NULL DEFAULT true,
    committee_id   bigint NOT NULL,
    user_id        bigint NOT NULL,
    role           character varying(24) NOT NULL DEFAULT 'OTRO',
    joined_on      date,
    left_on        date,
    created_by_id  bigint,
    updated_by_id  bigint,
    deleted_by_id  bigint,
    CONSTRAINT uq_observer_member       UNIQUE (committee_id, user_id),
    CONSTRAINT uq_observer_member_uuid  UNIQUE (uuid),
    CONSTRAINT ck_observer_member_role  CHECK (
        role IN ('PRESIDENTE','PERSONERO','DOCENTE','ORIENTADOR','PADRE','ESTUDIANTE','OTRO'))
);

-- ------------------------------------------------------------- 2.6 Sesiones
CREATE TABLE public.observer_committee_session (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       timestamp with time zone NOT NULL DEFAULT now(),
    updated_at       timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at       timestamp with time zone,
    uuid             uuid NOT NULL DEFAULT gen_random_uuid(),
    is_active        boolean NOT NULL DEFAULT true,
    committee_id     bigint NOT NULL,
    number           character varying(32) NOT NULL,
    session_date     timestamp with time zone NOT NULL,
    place            character varying(160) NOT NULL DEFAULT '',
    kind             character varying(12)  NOT NULL DEFAULT 'ORDINARIA',
    agenda           text NOT NULL DEFAULT '',
    development      text NOT NULL DEFAULT '',
    conclusions      text NOT NULL DEFAULT '',
    attendees_count  smallint NOT NULL DEFAULT 0,
    has_quorum       boolean NOT NULL DEFAULT false,
    status           character varying(14)  NOT NULL DEFAULT 'PROGRAMADA',
    minutes_file     character varying(100),
    created_by_id    bigint,
    updated_by_id    bigint,
    deleted_by_id    bigint,
    CONSTRAINT uq_observer_session_number UNIQUE (committee_id, number),
    CONSTRAINT uq_observer_session_uuid   UNIQUE (uuid),
    CONSTRAINT ck_observer_session_kind   CHECK (kind IN ('ORDINARIA','EXTRAORDINARIA')),
    CONSTRAINT ck_observer_session_status CHECK (
        status IN ('PROGRAMADA','REALIZADA','SIN_QUORUM','CANCELADA'))
);

-- ----------------------------------------------------------- 2.7 Decisiones
CREATE TABLE public.observer_decision (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at         timestamp with time zone NOT NULL DEFAULT now(),
    updated_at         timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at         timestamp with time zone,
    uuid               uuid NOT NULL DEFAULT gen_random_uuid(),
    is_active          boolean NOT NULL DEFAULT true,
    entry_id           bigint NOT NULL,
    session_id         bigint,
    kind               character varying(16)  NOT NULL DEFAULT 'FORMATIVA',
    description        text NOT NULL,
    manual_article     character varying(120) NOT NULL,
    effective_from     date,
    effective_to       date,
    decided_by_id      bigint,
    decided_at         timestamp with time zone NOT NULL DEFAULT now(),
    notified_at        timestamp with time zone,
    appeal_filed       boolean NOT NULL DEFAULT false,
    appeal_text        text NOT NULL DEFAULT '',
    appeal_resolution  text NOT NULL DEFAULT '',
    created_by_id      bigint,
    updated_by_id      bigint,
    deleted_by_id      bigint,
    CONSTRAINT uq_observer_decision_uuid UNIQUE (uuid),
    CONSTRAINT ck_observer_decision_kind CHECK (
        kind IN ('FORMATIVA','CORRECTIVA','REMISION','ABSOLUCION','OTRA')),
    CONSTRAINT ck_observer_decision_dates CHECK (
        effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from),
    -- RN-C-08: toda decision se sustenta en el manual de convivencia.
    CONSTRAINT ck_observer_decision_article CHECK (length(btrim(manual_article)) > 0)
);

-- ------------------------------------------------- 2.8 Trazabilidad del caso
CREATE TABLE public.observer_status_log (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       timestamp with time zone NOT NULL DEFAULT now(),
    updated_at       timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at       timestamp with time zone,
    uuid             uuid NOT NULL DEFAULT gen_random_uuid(),
    is_active        boolean NOT NULL DEFAULT true,
    entry_id         bigint NOT NULL,
    previous_status  character varying(16) NOT NULL DEFAULT '',
    new_status       character varying(16) NOT NULL,
    reason           text NOT NULL DEFAULT '',
    changed_at       timestamp with time zone NOT NULL DEFAULT now(),
    changed_by_id    bigint,
    created_by_id    bigint,
    updated_by_id    bigint,
    deleted_by_id    bigint,
    CONSTRAINT uq_observer_status_log_uuid UNIQUE (uuid)
);

-- ------------------------------------------------- 2.9 Reglas de alerta
CREATE TABLE public.observer_alert_rule (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     timestamp with time zone NOT NULL DEFAULT now(),
    updated_at     timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at     timestamp with time zone,
    uuid           uuid NOT NULL DEFAULT gen_random_uuid(),
    is_active      boolean NOT NULL DEFAULT true,
    code           character varying(32)  NOT NULL,
    name           character varying(180) NOT NULL,
    rule_type      character varying(24)  NOT NULL,
    threshold      numeric(8,2) NOT NULL DEFAULT 0,
    window_days    smallint NOT NULL DEFAULT 30,
    severity       character varying(12)  NOT NULL DEFAULT 'ADVERTENCIA',
    notify_role    character varying(40)  NOT NULL DEFAULT '',
    description    text NOT NULL DEFAULT '',
    created_by_id  bigint,
    updated_by_id  bigint,
    deleted_by_id  bigint,
    CONSTRAINT uq_observer_alert_rule_code UNIQUE (code),
    CONSTRAINT uq_observer_alert_rule_uuid UNIQUE (uuid),
    CONSTRAINT ck_observer_alert_rule_type CHECK (
        rule_type IN ('REINCIDENCIA','INASISTENCIA','RENDIMIENTO','COMPROMISO_INCUMPLIDO','TIPO_III')),
    CONSTRAINT ck_observer_alert_rule_sev  CHECK (severity IN ('INFO','ADVERTENCIA','CRITICA')),
    CONSTRAINT ck_observer_alert_rule_win  CHECK (window_days > 0)
);

-- -------------------------------------------------------- 2.10 Alertas
CREATE TABLE public.observer_alert (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       timestamp with time zone NOT NULL DEFAULT now(),
    updated_at       timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at       timestamp with time zone,
    uuid             uuid NOT NULL DEFAULT gen_random_uuid(),
    is_active        boolean NOT NULL DEFAULT true,
    rule_id          bigint NOT NULL,
    student_id       bigint NOT NULL,
    entry_id         bigint,
    school_year_id   bigint NOT NULL,
    level            character varying(12)  NOT NULL DEFAULT 'ADVERTENCIA',
    title            character varying(200) NOT NULL,
    message          text NOT NULL DEFAULT '',
    measured_value   numeric(8,2),
    status           character varying(12)  NOT NULL DEFAULT 'ABIERTA',
    attended_by_id   bigint,
    attended_at      timestamp with time zone,
    action_taken     text NOT NULL DEFAULT '',
    created_by_id    bigint,
    updated_by_id    bigint,
    deleted_by_id    bigint,
    CONSTRAINT uq_observer_alert_uuid  UNIQUE (uuid),
    CONSTRAINT ck_observer_alert_level CHECK (level IN ('INFO','ADVERTENCIA','CRITICA')),
    CONSTRAINT ck_observer_alert_status CHECK (status IN ('ABIERTA','ATENDIDA','DESCARTADA'))
);


-- ============================================================================
--  LLAVES FORANEAS
--  DEFERRABLE INITIALLY DEFERRED: misma convencion que el sistema (Django).
-- ============================================================================

-- ---- Incapacidades: auditoria ----
ALTER TABLE public.incapacity_type
    ADD CONSTRAINT fk_inc_type_created FOREIGN KEY (created_by_id) REFERENCES public.users_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_inc_type_updated FOREIGN KEY (updated_by_id) REFERENCES public.users_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_inc_type_deleted FOREIGN KEY (deleted_by_id) REFERENCES public.users_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

-- ---- Incapacidad: dominio ----
ALTER TABLE public.incapacity
    ADD CONSTRAINT fk_inc_student   FOREIGN KEY (student_id)          REFERENCES public.student(id)               ON DELETE CASCADE  DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_inc_teacher   FOREIGN KEY (teacher_id)          REFERENCES public.teacher(id)               ON DELETE CASCADE  DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_inc_subjuser  FOREIGN KEY (subject_user_id)     REFERENCES public.users_user(id)            ON DELETE CASCADE  DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_inc_type      FOREIGN KEY (incapacity_type_id)  REFERENCES public.incapacity_type(id)       ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_inc_year      FOREIGN KEY (school_year_id)      REFERENCES public.academic_school_year(id)  ON DELETE CASCADE  DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_inc_campus    FOREIGN KEY (campus_id)           REFERENCES public.institution_campus(id)    ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_inc_parent    FOREIGN KEY (parent_id)           REFERENCES public.incapacity(id)            ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_inc_absence   FOREIGN KEY (teacher_absence_id)  REFERENCES public.teacher_absence(id)       ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_inc_document  FOREIGN KEY (student_document_id) REFERENCES public.student_document(id)      ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_inc_verified  FOREIGN KEY (verified_by_id)      REFERENCES public.users_user(id)            ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_inc_approved  FOREIGN KEY (approved_by_id)      REFERENCES public.users_user(id)            ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_inc_reported  FOREIGN KEY (reported_by_id)      REFERENCES public.users_user(id)            ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_inc_created   FOREIGN KEY (created_by_id)       REFERENCES public.users_user(id)            ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_inc_updated   FOREIGN KEY (updated_by_id)       REFERENCES public.users_user(id)            ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_inc_deleted   FOREIGN KEY (deleted_by_id)       REFERENCES public.users_user(id)            ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.incapacity_attachment
    ADD CONSTRAINT fk_inc_att_incapacity FOREIGN KEY (incapacity_id) REFERENCES public.incapacity(id)  ON DELETE CASCADE  DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_inc_att_created    FOREIGN KEY (created_by_id) REFERENCES public.users_user(id)  ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_inc_att_updated    FOREIGN KEY (updated_by_id) REFERENCES public.users_user(id)  ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_inc_att_deleted    FOREIGN KEY (deleted_by_id) REFERENCES public.users_user(id)  ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.incapacity_history
    ADD CONSTRAINT fk_inc_hist_incapacity FOREIGN KEY (incapacity_id) REFERENCES public.incapacity(id) ON DELETE CASCADE  DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_inc_hist_changed    FOREIGN KEY (changed_by_id) REFERENCES public.users_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_inc_hist_created    FOREIGN KEY (created_by_id) REFERENCES public.users_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_inc_hist_updated    FOREIGN KEY (updated_by_id) REFERENCES public.users_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_inc_hist_deleted    FOREIGN KEY (deleted_by_id) REFERENCES public.users_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.incapacity_attendance_link
    ADD CONSTRAINT fk_inc_link_incapacity FOREIGN KEY (incapacity_id)        REFERENCES public.incapacity(id)        ON DELETE CASCADE  DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_inc_link_record     FOREIGN KEY (attendance_record_id) REFERENCES public.attendance_record(id) ON DELETE CASCADE  DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_inc_link_created    FOREIGN KEY (created_by_id)        REFERENCES public.users_user(id)        ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_inc_link_updated    FOREIGN KEY (updated_by_id)        REFERENCES public.users_user(id)        ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_inc_link_deleted    FOREIGN KEY (deleted_by_id)        REFERENCES public.users_user(id)        ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

-- ---- Convivencia ----
ALTER TABLE public.observer_evidence
    ADD CONSTRAINT fk_obs_ev_entry   FOREIGN KEY (entry_id)      REFERENCES public.observer_entry(id) ON DELETE CASCADE  DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_ev_created FOREIGN KEY (created_by_id) REFERENCES public.users_user(id)     ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_ev_updated FOREIGN KEY (updated_by_id) REFERENCES public.users_user(id)     ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_ev_deleted FOREIGN KEY (deleted_by_id) REFERENCES public.users_user(id)     ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.observer_summons
    ADD CONSTRAINT fk_obs_sum_entry    FOREIGN KEY (entry_id)            REFERENCES public.observer_entry(id)   ON DELETE CASCADE  DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_sum_guardian FOREIGN KEY (guardian_id)         REFERENCES public.student_guardian(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_sum_resched  FOREIGN KEY (rescheduled_from_id) REFERENCES public.observer_summons(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_sum_created  FOREIGN KEY (created_by_id)       REFERENCES public.users_user(id)       ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_sum_updated  FOREIGN KEY (updated_by_id)       REFERENCES public.users_user(id)       ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_sum_deleted  FOREIGN KEY (deleted_by_id)       REFERENCES public.users_user(id)       ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.observer_commitment
    ADD CONSTRAINT fk_obs_com_entry    FOREIGN KEY (entry_id)            REFERENCES public.observer_entry(id)   ON DELETE CASCADE  DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_com_summons  FOREIGN KEY (summons_id)          REFERENCES public.observer_summons(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_com_resp     FOREIGN KEY (responsible_user_id) REFERENCES public.users_user(id)       ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_com_verified FOREIGN KEY (verified_by_id)      REFERENCES public.users_user(id)       ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_com_created  FOREIGN KEY (created_by_id)       REFERENCES public.users_user(id)       ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_com_updated  FOREIGN KEY (updated_by_id)       REFERENCES public.users_user(id)       ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_com_deleted  FOREIGN KEY (deleted_by_id)       REFERENCES public.users_user(id)       ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.observer_committee
    ADD CONSTRAINT fk_obs_cmt_year    FOREIGN KEY (school_year_id) REFERENCES public.academic_school_year(id) ON DELETE CASCADE  DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_cmt_campus  FOREIGN KEY (campus_id)      REFERENCES public.institution_campus(id)   ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_cmt_created FOREIGN KEY (created_by_id)  REFERENCES public.users_user(id)           ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_cmt_updated FOREIGN KEY (updated_by_id)  REFERENCES public.users_user(id)           ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_cmt_deleted FOREIGN KEY (deleted_by_id)  REFERENCES public.users_user(id)           ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.observer_committee_member
    ADD CONSTRAINT fk_obs_mem_committee FOREIGN KEY (committee_id)  REFERENCES public.observer_committee(id) ON DELETE CASCADE  DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_mem_user      FOREIGN KEY (user_id)       REFERENCES public.users_user(id)         ON DELETE CASCADE  DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_mem_created   FOREIGN KEY (created_by_id) REFERENCES public.users_user(id)         ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_mem_updated   FOREIGN KEY (updated_by_id) REFERENCES public.users_user(id)         ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_mem_deleted   FOREIGN KEY (deleted_by_id) REFERENCES public.users_user(id)         ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.observer_committee_session
    ADD CONSTRAINT fk_obs_ses_committee FOREIGN KEY (committee_id)  REFERENCES public.observer_committee(id) ON DELETE CASCADE  DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_ses_created   FOREIGN KEY (created_by_id) REFERENCES public.users_user(id)         ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_ses_updated   FOREIGN KEY (updated_by_id) REFERENCES public.users_user(id)         ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_ses_deleted   FOREIGN KEY (deleted_by_id) REFERENCES public.users_user(id)         ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.observer_decision
    ADD CONSTRAINT fk_obs_dec_entry   FOREIGN KEY (entry_id)      REFERENCES public.observer_entry(id)              ON DELETE CASCADE  DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_dec_session FOREIGN KEY (session_id)    REFERENCES public.observer_committee_session(id)  ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_dec_by      FOREIGN KEY (decided_by_id) REFERENCES public.users_user(id)                  ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_dec_created FOREIGN KEY (created_by_id) REFERENCES public.users_user(id)                  ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_dec_updated FOREIGN KEY (updated_by_id) REFERENCES public.users_user(id)                  ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_dec_deleted FOREIGN KEY (deleted_by_id) REFERENCES public.users_user(id)                  ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.observer_status_log
    ADD CONSTRAINT fk_obs_log_entry   FOREIGN KEY (entry_id)      REFERENCES public.observer_entry(id) ON DELETE CASCADE  DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_log_changed FOREIGN KEY (changed_by_id) REFERENCES public.users_user(id)     ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_log_created FOREIGN KEY (created_by_id) REFERENCES public.users_user(id)     ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_log_updated FOREIGN KEY (updated_by_id) REFERENCES public.users_user(id)     ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_log_deleted FOREIGN KEY (deleted_by_id) REFERENCES public.users_user(id)     ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.observer_alert_rule
    ADD CONSTRAINT fk_obs_rule_created FOREIGN KEY (created_by_id) REFERENCES public.users_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_rule_updated FOREIGN KEY (updated_by_id) REFERENCES public.users_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_rule_deleted FOREIGN KEY (deleted_by_id) REFERENCES public.users_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.observer_alert
    ADD CONSTRAINT fk_obs_alert_rule     FOREIGN KEY (rule_id)        REFERENCES public.observer_alert_rule(id)  ON DELETE CASCADE  DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_alert_student  FOREIGN KEY (student_id)     REFERENCES public.student(id)              ON DELETE CASCADE  DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_alert_entry    FOREIGN KEY (entry_id)       REFERENCES public.observer_entry(id)       ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_alert_year     FOREIGN KEY (school_year_id) REFERENCES public.academic_school_year(id) ON DELETE CASCADE  DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_alert_attended FOREIGN KEY (attended_by_id) REFERENCES public.users_user(id)           ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_alert_created  FOREIGN KEY (created_by_id)  REFERENCES public.users_user(id)           ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_alert_updated  FOREIGN KEY (updated_by_id)  REFERENCES public.users_user(id)           ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_obs_alert_deleted  FOREIGN KEY (deleted_by_id)  REFERENCES public.users_user(id)           ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;


-- ============================================================================
--  INDICES
-- ============================================================================

-- ---- Incapacidades ----
CREATE INDEX ix_incapacity_type_active   ON public.incapacity_type (is_active, "order");
CREATE INDEX ix_incapacity_type_scope    ON public.incapacity_type (applies_to);

CREATE INDEX ix_incapacity_student_date  ON public.incapacity (student_id, start_date DESC);
CREATE INDEX ix_incapacity_teacher_date  ON public.incapacity (teacher_id, start_date DESC);
CREATE INDEX ix_incapacity_status_year   ON public.incapacity (status, school_year_id);
CREATE INDEX ix_incapacity_range         ON public.incapacity (start_date, end_date);
CREATE INDEX ix_incapacity_subject_type  ON public.incapacity (subject_type);
CREATE INDEX ix_incapacity_folio         ON public.incapacity (folio);
CREATE INDEX ix_incapacity_deleted       ON public.incapacity (deleted_at);

CREATE INDEX ix_inc_attachment_incapacity ON public.incapacity_attachment (incapacity_id);
CREATE INDEX ix_inc_attachment_conf       ON public.incapacity_attachment (is_confidential);
CREATE INDEX ix_inc_history_incapacity    ON public.incapacity_history (incapacity_id, changed_at DESC);
CREATE INDEX ix_inc_link_record           ON public.incapacity_attendance_link (attendance_record_id);
CREATE INDEX ix_inc_link_reverted         ON public.incapacity_attendance_link (reverted_at);

-- ---- Convivencia ----
CREATE INDEX ix_obs_evidence_entry     ON public.observer_evidence (entry_id);
CREATE INDEX ix_obs_evidence_conf      ON public.observer_evidence (is_confidential);

CREATE INDEX ix_obs_summons_entry      ON public.observer_summons (entry_id, scheduled_at DESC);
CREATE INDEX ix_obs_summons_status     ON public.observer_summons (status, scheduled_at);
CREATE INDEX ix_obs_summons_guardian   ON public.observer_summons (guardian_id);

CREATE INDEX ix_obs_commitment_entry   ON public.observer_commitment (entry_id);
CREATE INDEX ix_obs_commitment_due     ON public.observer_commitment (status, due_date);

CREATE INDEX ix_obs_committee_year     ON public.observer_committee (school_year_id);
CREATE INDEX ix_obs_committee_status   ON public.observer_committee (status);
CREATE INDEX ix_obs_member_committee   ON public.observer_committee_member (committee_id);
CREATE INDEX ix_obs_member_user        ON public.observer_committee_member (user_id);

CREATE INDEX ix_obs_session_committee  ON public.observer_committee_session (committee_id, session_date DESC);
CREATE INDEX ix_obs_session_status     ON public.observer_committee_session (status, has_quorum);

CREATE INDEX ix_obs_decision_entry     ON public.observer_decision (entry_id);
CREATE INDEX ix_obs_decision_session   ON public.observer_decision (session_id);
CREATE INDEX ix_obs_decision_kind      ON public.observer_decision (kind);

CREATE INDEX ix_obs_status_entry       ON public.observer_status_log (entry_id, changed_at DESC);
CREATE INDEX ix_obs_status_new         ON public.observer_status_log (new_status);

CREATE INDEX ix_obs_rule_active        ON public.observer_alert_rule (is_active, rule_type);

CREATE INDEX ix_obs_alert_student      ON public.observer_alert (student_id, created_at DESC);
CREATE INDEX ix_obs_alert_open         ON public.observer_alert (status, level);
CREATE INDEX ix_obs_alert_rule         ON public.observer_alert (rule_id);

-- Una sola alerta ABIERTA por regla, estudiante y ano lectivo.
CREATE UNIQUE INDEX uq_obs_alert_open
    ON public.observer_alert (rule_id, student_id, school_year_id)
    WHERE status = 'ABIERTA' AND deleted_at IS NULL;

-- Un solo comite VIGENTE por ano lectivo y sede.
CREATE UNIQUE INDEX uq_obs_committee_current
    ON public.observer_committee (school_year_id, COALESCE(campus_id, 0))
    WHERE status = 'VIGENTE' AND deleted_at IS NULL;


-- ============================================================================
--  DATOS DE CONFIGURACION INICIAL (parametrizables desde la interfaz)
-- ============================================================================

INSERT INTO public.incapacity_type
    (code, name, description, "order", applies_to, requires_support, requires_diagnosis, justifies_attendance, max_days)
VALUES
    ('ENF_GENERAL',       'Enfermedad general',              'Incapacidad por enfermedad comun',            1, 'TODOS',      true,  false, true,  180),
    ('ACCIDENTE_TRABAJO', 'Accidente de trabajo',            'Accidente laboral reportado a la ARL',        2, 'DOCENTE',    true,  true,  true,  180),
    ('ACCIDENTE_ESCOLAR', 'Accidente escolar',               'Accidente ocurrido en la institucion',        3, 'ESTUDIANTE', true,  false, true,  60),
    ('MATERNIDAD',        'Licencia de maternidad',          'Licencia de maternidad',                      4, 'TODOS',      true,  false, true,  126),
    ('PATERNIDAD',        'Licencia de paternidad',          'Licencia de paternidad',                      5, 'TODOS',      true,  false, true,  14),
    ('CITA_MEDICA',       'Cita medica',                     'Ausencia por cita medica programada',         6, 'TODOS',      true,  false, true,  1),
    ('AISLAMIENTO',       'Aislamiento preventivo',          'Aislamiento por indicacion sanitaria',        7, 'TODOS',      true,  false, true,  14),
    ('OTRA',              'Otra',                            'Otro tipo de incapacidad',                    8, 'TODOS',      true,  false, true,  NULL);

INSERT INTO public.observer_alert_rule
    (code, name, rule_type, threshold, window_days, severity, notify_role, description)
VALUES
    ('REINC_TIPO_I',   'Reincidencia en situaciones tipo I',   'REINCIDENCIA',           3,  30, 'ADVERTENCIA', 'TUTOR',       'Tres o mas situaciones tipo I en 30 dias'),
    ('REINC_TIPO_II',  'Reincidencia en situaciones tipo II',  'REINCIDENCIA',           2,  60, 'CRITICA',     'COORDINADOR', 'Dos o mas situaciones tipo II en 60 dias'),
    ('SIT_TIPO_III',   'Situacion tipo III reportada',         'TIPO_III',               1,   1, 'CRITICA',     'RECTOR',      'Toda situacion tipo III genera alerta inmediata'),
    ('INASISTENCIA',   'Inasistencia recurrente',              'INASISTENCIA',          20,  30, 'ADVERTENCIA', 'TUTOR',       'Mas del 20% de inasistencia no justificada en 30 dias'),
    ('BAJO_RENDIM',    'Bajo rendimiento academico',           'RENDIMIENTO',            3,  90, 'ADVERTENCIA', 'COORDINADOR', 'Tres o mas asignaturas por debajo del desempeno basico'),
    ('COMP_INCUMP',    'Compromisos incumplidos',              'COMPROMISO_INCUMPLIDO',  2,  90, 'CRITICA',     'COORDINADOR', 'Dos o mas compromisos incumplidos en 90 dias');


-- ============================================================================
--  VERIFICACION
-- ============================================================================
DO $$
DECLARE
    tablas integer;
BEGIN
    SELECT count(*) INTO tablas
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name IN ('incapacity_type','incapacity','incapacity_attachment','incapacity_history',
                         'incapacity_attendance_link','observer_evidence','observer_summons',
                         'observer_commitment','observer_committee','observer_committee_member',
                         'observer_committee_session','observer_decision','observer_status_log',
                         'observer_alert_rule','observer_alert');
    IF tablas <> 15 THEN
        RAISE EXCEPTION 'Se esperaban 15 tablas de la extension y se encontraron %.', tablas;
    END IF;
    RAISE NOTICE 'Extension aplicada: 15 tablas creadas correctamente.';
END $$;

COMMIT;

-- ============================================================================
--  NOTA SOBRE observer_entry.status
-- ----------------------------------------------------------------------------
--  El estado ESCALADO_COMITE (15 caracteres) cabe en la columna existente
--  character varying(16) y la columna NO tiene restriccion CHECK, por lo que
--  NO se requiere ningun ALTER TABLE. El valor se habilita en el modelo de
--  Django (choices), que es validacion de aplicacion, no del motor.
--
--  Se deja documentado que si en el futuro se decidiera restringir el dominio
--  a nivel de base, la sentencia seria:
--
--     ALTER TABLE public.observer_entry
--         ADD CONSTRAINT ck_observer_entry_status CHECK (
--             status IN ('ABIERTA','EN_SEGUIMIENTO','ESCALADO_COMITE','CERRADA','ANULADA'));
--
--  No se incluye en esta migracion para no imponer una restriccion nueva
--  sobre una tabla en produccion.
-- ============================================================================
