# Generated by Django 5.2.17 on 2026-08-23 07:09

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('code', models.CharField(db_index=True, max_length=32, verbose_name='Codigo')),
                ('name', models.CharField(max_length=180, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Orden')),
                ('severity', models.CharField(choices=[('TIPO_I', 'Situacion tipo I - Leve'), ('TIPO_II', 'Situacion tipo II - Grave'), ('TIPO_III', 'Situacion tipo III - Gravisima'), ('POSITIVA', 'Reconocimiento positivo'), ('ACADEMICA', 'Seguimiento academico'), ('INFORMATIVA', 'Informativa')], default='TIPO_I', max_length=12, verbose_name='Tipificacion')),
                ('color', models.CharField(default='#F59E0B', max_length=20, verbose_name='Color')),
                ('requires_guardian', models.BooleanField(default=False, verbose_name='Requiere citacion de acudiente')),
                ('requires_commitment', models.BooleanField(default=False, verbose_name='Requiere acta de compromiso')),
                ('manual_article', models.CharField(blank=True, max_length=80, verbose_name='Articulo del manual')),
            ],
            options={
                'verbose_name': 'Tipo de observacion',
                'verbose_name_plural': 'Tipos de observacion',
                'db_table': 'observer_category',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ObserverEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Fecha del hecho')),
                ('place', models.CharField(blank=True, max_length=120, verbose_name='Lugar')),
                ('description', models.TextField(verbose_name='Descripcion de la situacion')),
                ('student_version', models.TextField(blank=True, verbose_name='Version del estudiante')),
                ('actions_taken', models.TextField(blank=True, verbose_name='Acciones adoptadas')),
                ('commitments', models.TextField(blank=True, verbose_name='Compromisos')),
                ('guardian_notified', models.BooleanField(default=False, verbose_name='Acudiente notificado')),
                ('guardian_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Notificado el')),
                ('student_signed', models.BooleanField(default=False, verbose_name='Firmado por el estudiante')),
                ('guardian_signed', models.BooleanField(default=False, verbose_name='Firmado por el acudiente')),
                ('status', models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_SEGUIMIENTO', 'En seguimiento'), ('CERRADA', 'Cerrada'), ('ANULADA', 'Anulada')], default='ABIERTA', max_length=16, verbose_name='Estado')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='observer/%Y/%m/', verbose_name='Anexo')),
            ],
            options={
                'verbose_name': 'Anotacion del observador',
                'verbose_name_plural': 'Observador',
                'db_table': 'observer_entry',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObserverFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha')),
                ('description', models.TextField(verbose_name='Seguimiento')),
                ('result', models.CharField(choices=[('POSITIVO', 'Positivo'), ('PARCIAL', 'Parcial'), ('NEGATIVO', 'Negativo'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=16, verbose_name='Resultado')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'db_table': 'observer_follow_up',
                'ordering': ['-date'],
            },
        ),
    ]
