# Generated by Django 5.2.17 on 2026-08-23 07:09

import core.users.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('color', models.CharField(default='#4F46E5', max_length=20, verbose_name='Color')),
                ('is_system', models.BooleanField(default=False, verbose_name='Rol del sistema')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('landing_url', models.CharField(default='dashboard:index', max_length=120, verbose_name='Ruta de inicio')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'users_role',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('icon', models.CharField(default='circle', max_length=48, verbose_name='Icono')),
                ('url_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Ruta')),
                ('group', models.CharField(default='Principal', max_length=60, verbose_name='Grupo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('show_in_menu', models.BooleanField(default=True, verbose_name='Visible en el menu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='users.module', verbose_name='Modulo padre')),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulos',
                'db_table': 'users_module',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electronico')),
                ('first_name', models.CharField(max_length=120, verbose_name='Nombres')),
                ('last_name', models.CharField(blank=True, max_length=120, verbose_name='Apellidos')),
                ('document_type', models.CharField(choices=[('TI', 'Tarjeta de Identidad'), ('CC', 'Cedula de Ciudadania'), ('CE', 'Cedula de Extranjeria'), ('RC', 'Registro Civil'), ('PA', 'Pasaporte'), ('NUIP', 'NUIP'), ('PEP', 'Permiso Especial de Permanencia'), ('NES', 'Numero Establecido por la Secretaria')], default='CC', max_length=8, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Numero de documento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'No informa')], default='N', max_length=1, verbose_name='Genero')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Telefono')),
                ('mobile', models.CharField(blank=True, max_length=32, verbose_name='Celular')),
                ('address', models.CharField(blank=True, max_length=240, verbose_name='Direccion')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Ciudad')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/photos/', verbose_name='Fotografia')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Acceso al admin')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Correo verificado')),
                ('must_change_password', models.BooleanField(default=False, verbose_name='Debe cambiar la contrasena')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='2FA activo')),
                ('two_factor_enforced', models.BooleanField(default=False, verbose_name='2FA obligatorio')),
                ('last_password_change', models.DateTimeField(blank=True, null=True, verbose_name='Ultimo cambio de contrasena')),
                ('failed_login_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Intentos fallidos')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado hasta')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Ultima IP')),
                ('theme', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('auto', 'Sistema')], default='light', max_length=10, verbose_name='Tema')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='institutions.institution', verbose_name='Institucion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.role', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'users_user',
                'ordering': ['first_name', 'last_name'],
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', core.users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('can_view', models.BooleanField(default=False, verbose_name='Consultar')),
                ('can_create', models.BooleanField(default=False, verbose_name='Crear')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Editar')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Eliminar')),
                ('can_export', models.BooleanField(default=False, verbose_name='Exportar')),
                ('can_approve', models.BooleanField(default=False, verbose_name='Aprobar')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='users.module', verbose_name='Modulo')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='users.role', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Permiso de rol',
                'verbose_name_plural': 'Permisos por rol',
                'db_table': 'users_role_permission',
                'ordering': ['role__order', 'module__order'],
            },
        ),
        migrations.CreateModel(
            name='UserCredentialCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('plain_password', models.CharField(max_length=64, verbose_name='Contrasena entregada')),
                ('delivered', models.BooleanField(default=False, verbose_name='Entregado')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('notes', models.CharField(blank=True, max_length=240, verbose_name='Observaciones')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_credentials', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificado de credenciales',
                'verbose_name_plural': 'Certificados de credenciales',
                'db_table': 'users_credential_certificate',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('action', models.CharField(max_length=20, verbose_name='Accion')),
                ('granted', models.BooleanField(default=True, verbose_name='Concedido')),
                ('reason', models.CharField(blank=True, max_length=240, verbose_name='Motivo')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.module', verbose_name='Modulo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Permiso individual',
                'verbose_name_plural': 'Permisos individuales',
                'db_table': 'users_user_module_permission',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('sidebar_collapsed', models.BooleanField(default=False, verbose_name='Menu contraido')),
                ('density', models.CharField(choices=[('comfortable', 'Comoda'), ('compact', 'Compacta')], default='comfortable', max_length=12, verbose_name='Densidad')),
                ('default_module', models.CharField(blank=True, max_length=80, verbose_name='Modulo inicial')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notificaciones por correo')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Notificaciones en plataforma')),
                ('items_per_page', models.PositiveSmallIntegerField(default=25, verbose_name='Registros por pagina')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de usuario',
                'verbose_name_plural': 'Preferencias de usuario',
                'db_table': 'users_preference',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['document_number'], name='users_user_documen_9d6cd6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='users_user_role_id_08cc48_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'module')},
        ),
        migrations.AlterUniqueTogether(
            name='usermodulepermission',
            unique_together={('user', 'module', 'action')},
        ),
    ]
