# Generated by Django 5.2.17 on 2026-08-23 07:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('code', models.CharField(max_length=32, verbose_name='Codigo')),
                ('name', models.CharField(max_length=160, verbose_name='Nombre de la sede')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Direccion')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefono')),
                ('is_main', models.BooleanField(default=False, verbose_name='Sede principal')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'db_table': 'institution_campus',
                'ordering': ['-is_main', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Codigo DANE')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la institucion')),
                ('short_name', models.CharField(blank=True, max_length=80, verbose_name='Nombre corto')),
                ('nit', models.CharField(blank=True, max_length=32, verbose_name='NIT')),
                ('resolution', models.CharField(blank=True, max_length=200, verbose_name='Resolucion de aprobacion')),
                ('nature', models.CharField(choices=[('OFICIAL', 'Oficial'), ('PRIVADA', 'Privada'), ('MIXTA', 'Mixta')], default='PRIVADA', max_length=12, verbose_name='Naturaleza')),
                ('calendar', models.CharField(choices=[('A', 'Calendario A'), ('B', 'Calendario B'), ('C', 'Calendario C')], default='A', max_length=1, verbose_name='Calendario')),
                ('country', models.CharField(default='Colombia', max_length=80, verbose_name='Pais')),
                ('department', models.CharField(blank=True, max_length=80, verbose_name='Departamento')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='Ciudad')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Direccion')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo institucional')),
                ('website', models.URLField(blank=True, verbose_name='Sitio web')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institution/', verbose_name='Logotipo')),
                ('seal', models.ImageField(blank=True, null=True, upload_to='institution/', verbose_name='Sello')),
                ('rector_name', models.CharField(blank=True, max_length=160, verbose_name='Nombre del rector')),
                ('rector_document', models.CharField(blank=True, max_length=32, verbose_name='Documento del rector')),
                ('rector_signature', models.ImageField(blank=True, null=True, upload_to='institution/', verbose_name='Firma del rector')),
                ('secretary_name', models.CharField(blank=True, max_length=160, verbose_name='Nombre de secretaria')),
                ('secretary_signature', models.ImageField(blank=True, null=True, upload_to='institution/', verbose_name='Firma de secretaria')),
                ('motto', models.CharField(blank=True, max_length=200, verbose_name='Lema')),
                ('mission', models.TextField(blank=True, verbose_name='Mision')),
                ('vision', models.TextField(blank=True, verbose_name='Vision')),
                ('primary_color', models.CharField(default='#4F46E5', max_length=20, verbose_name='Color primario')),
                ('accent_color', models.CharField(default='#0EA5E9', max_length=20, verbose_name='Color de acento')),
                ('is_default', models.BooleanField(default=False, verbose_name='Institucion principal')),
            ],
            options={
                'verbose_name': 'Institucion',
                'verbose_name_plural': 'Instituciones',
                'db_table': 'institution',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionalCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=160, verbose_name='Nombre')),
                ('event_type', models.CharField(choices=[('ACADEMICO', 'Academico'), ('FESTIVO', 'Festivo'), ('INSTITUCIONAL', 'Institucional'), ('EVALUACION', 'Evaluacion'), ('RECESO', 'Receso')], default='ACADEMICO', max_length=20, verbose_name='Tipo')),
                ('start_date', models.DateField(verbose_name='Fecha inicial')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha final')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Fecha del calendario',
                'verbose_name_plural': 'Calendario institucional',
                'db_table': 'institution_calendar',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('code', models.CharField(db_index=True, max_length=32, verbose_name='Codigo')),
                ('name', models.CharField(max_length=180, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Orden')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Hora de finalizacion')),
            ],
            options={
                'verbose_name': 'Jornada',
                'verbose_name_plural': 'Jornadas',
                'db_table': 'institution_shift',
                'ordering': ['order', 'name'],
            },
        ),
    ]
