# Generated by Django 5.2.17 on 2026-08-23 07:09

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Identificador URL')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('audience', models.CharField(choices=[('PUBLICO', 'Publico (sin autenticacion)'), ('ESTUDIANTES', 'Estudiantes'), ('DOCENTES', 'Docentes'), ('ACUDIENTES', 'Acudientes'), ('INTERNO', 'Usuarios autenticados')], default='INTERNO', max_length=12, verbose_name='Dirigido a')),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado'), ('CERRADO', 'Cerrado')], default='BORRADOR', max_length=10, verbose_name='Estado')),
                ('opens_at', models.DateTimeField(blank=True, null=True, verbose_name='Disponible desde')),
                ('closes_at', models.DateTimeField(blank=True, null=True, verbose_name='Disponible hasta')),
                ('allow_multiple', models.BooleanField(default=False, verbose_name='Permite multiples respuestas')),
                ('notify_email', models.EmailField(blank=True, max_length=254, verbose_name='Notificar a')),
                ('success_message', models.CharField(default='Su respuesta fue registrada correctamente.', max_length=240, verbose_name='Mensaje de confirmacion')),
                ('submissions_count', models.PositiveIntegerField(default=0, verbose_name='Respuestas')),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
                'db_table': 'extension_form',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('key', models.CharField(max_length=60, verbose_name='Clave')),
                ('label', models.CharField(max_length=200, verbose_name='Etiqueta')),
                ('field_type', models.CharField(choices=[('text', 'Texto corto'), ('textarea', 'Texto largo'), ('number', 'Numero'), ('email', 'Correo electronico'), ('date', 'Fecha'), ('time', 'Hora'), ('select', 'Lista desplegable'), ('radio', 'Opcion unica'), ('checkbox', 'Casillas multiples'), ('file', 'Archivo'), ('rating', 'Valoracion 1-5'), ('section', 'Titulo de seccion')], default='text', max_length=12, verbose_name='Tipo de campo')),
                ('placeholder', models.CharField(blank=True, max_length=160, verbose_name='Texto de ayuda')),
                ('help_text', models.CharField(blank=True, max_length=240, verbose_name='Descripcion')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='Opciones')),
                ('required', models.BooleanField(default=False, verbose_name='Obligatorio')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('width', models.CharField(choices=[('full', 'Completo'), ('half', 'Mitad'), ('third', 'Un tercio')], default='full', max_length=8, verbose_name='Ancho')),
            ],
            options={
                'verbose_name': 'Campo del formulario',
                'verbose_name_plural': 'Campos del formulario',
                'db_table': 'extension_form_field',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('data', models.JSONField(default=dict, verbose_name='Respuestas')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Enviado el')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('reviewed', models.BooleanField(default=False, verbose_name='Revisado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas internas')),
            ],
            options={
                'verbose_name': 'Respuesta de formulario',
                'verbose_name_plural': 'Respuestas de formularios',
                'db_table': 'extension_form_submission',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='VirtualSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=180, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('kind', models.CharField(choices=[('VIDEOCONFERENCIA', 'Videoconferencia'), ('BIBLIOTECA', 'Biblioteca digital'), ('PLATAFORMA', 'Plataforma externa'), ('REPOSITORIO', 'Repositorio'), ('APLICACION', 'Aplicacion institucional')], default='PLATAFORMA', max_length=18, verbose_name='Tipo')),
                ('url', models.URLField(verbose_name='Enlace')),
                ('icon', models.CharField(default='external', max_length=40, verbose_name='Icono')),
                ('color', models.CharField(default='#0EA5E9', max_length=20, verbose_name='Color')),
                ('audience', models.CharField(choices=[('TODOS', 'Toda la comunidad'), ('ESTUDIANTES', 'Estudiantes'), ('DOCENTES', 'Docentes'), ('ACUDIENTES', 'Acudientes')], default='TODOS', max_length=12, verbose_name='Dirigido a')),
                ('open_in_new_tab', models.BooleanField(default=True, verbose_name='Abrir en nueva pestana')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Accesos')),
            ],
            options={
                'verbose_name': 'Espacio virtual',
                'verbose_name_plural': 'Espacios virtuales',
                'db_table': 'extension_virtual_space',
                'ordering': ['order', 'name'],
            },
        ),
    ]
