# Generated by Django 5.2.17 on 2026-08-23 07:09

import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=180, verbose_name='Actividad')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, verbose_name='Porcentaje (%)')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('resource', models.FileField(blank=True, null=True, upload_to='recoveries/%Y/%m/', verbose_name='Material de apoyo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Actividad complementaria',
                'verbose_name_plural': 'Actividades complementarias',
                'db_table': 'recovery_activity',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryActivitySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Entregado el')),
                ('file', models.FileField(blank=True, null=True, upload_to='recoveries/submissions/%Y/%m/', verbose_name='Archivo')),
                ('comments', models.TextField(blank=True, verbose_name='Comentarios')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota')),
                ('feedback', models.TextField(blank=True, verbose_name='Retroalimentacion')),
            ],
            options={
                'verbose_name': 'Entrega de recuperacion',
                'verbose_name_plural': 'Entregas de recuperacion',
                'db_table': 'recovery_submission',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('previous_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota anterior')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota obtenida')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota definitiva')),
                ('status', models.CharField(choices=[('INSCRITO', 'Inscrito'), ('PRESENTO', 'Presento'), ('NO_PRESENTO', 'No presento'), ('APROBO', 'Aprobo'), ('REPROBO', 'Reprobo')], default='INSCRITO', max_length=12, verbose_name='Estado')),
                ('observation', models.TextField(blank=True, verbose_name='Observacion')),
                ('evaluated_at', models.DateTimeField(blank=True, null=True, verbose_name='Evaluado el')),
                ('applied_to_grade', models.BooleanField(default=False, verbose_name='Aplicado al boletin')),
            ],
            options={
                'verbose_name': 'Inscripcion a recuperacion',
                'verbose_name_plural': 'Inscripciones a recuperacion',
                'db_table': 'recovery_enrollment',
                'ordering': ['student__last_name'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('plan_type', models.CharField(choices=[('PERIODO', 'Recuperacion de periodo'), ('FINAL', 'Recuperacion final'), ('NIVELACION', 'Nivelacion'), ('HABILITACION', 'Habilitacion'), ('BILINGUE', 'Refuerzo bilingue')], default='PERIODO', max_length=12, verbose_name='Tipo')),
                ('name', models.CharField(max_length=180, verbose_name='Nombre del plan')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('objectives', models.TextField(blank=True, verbose_name='Objetivos')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de finalizacion')),
                ('evaluation_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de evaluacion')),
                ('maximum_score', models.DecimalField(decimal_places=2, default=Decimal('3.50'), max_digits=5, verbose_name='Nota maxima alcanzable')),
                ('status', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_CURSO', 'En curso'), ('EVALUADO', 'Evaluado'), ('CERRADO', 'Cerrado')], default='PROGRAMADO', max_length=12, verbose_name='Estado')),
                ('is_bilingual', models.BooleanField(default=False, verbose_name='Proceso bilingue')),
            ],
            options={
                'verbose_name': 'Plan de recuperacion',
                'verbose_name_plural': 'Planes de recuperacion',
                'db_table': 'recovery_plan',
                'ordering': ['-start_date'],
            },
        ),
    ]
