# Generated by Django 5.2.17 on 2026-08-23 07:09

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emphasis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('code', models.CharField(db_index=True, max_length=32, verbose_name='Codigo')),
                ('name', models.CharField(max_length=180, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Orden')),
                ('kind', models.CharField(choices=[('DEPORTIVO', 'Deportivo'), ('ARTISTICO', 'Artistico'), ('TECNICO', 'Tecnico'), ('ACADEMICO', 'Academico'), ('CULTURAL', 'Cultural'), ('TECNOLOGICO', 'Tecnologico')], default='ACADEMICO', max_length=14, verbose_name='Tipo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='emphases/', verbose_name='Imagen')),
                ('color', models.CharField(default='#0EA5E9', max_length=20, verbose_name='Color')),
                ('requirements', models.TextField(blank=True, verbose_name='Requisitos')),
            ],
            options={
                'verbose_name': 'Enfasis',
                'verbose_name_plural': 'Enfasis y disciplinas',
                'db_table': 'emphasis',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmphasisEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('enrolled_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de inscripcion')),
                ('status', models.CharField(choices=[('ACTIVA', 'Activa'), ('RETIRADA', 'Retirada'), ('LISTA_ESPERA', 'Lista de espera'), ('FINALIZADA', 'Finalizada')], default='ACTIVA', max_length=14, verbose_name='Estado')),
                ('priority', models.PositiveSmallIntegerField(default=1, verbose_name='Prioridad')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valoracion')),
                ('observation', models.CharField(blank=True, max_length=240, verbose_name='Observacion')),
            ],
            options={
                'verbose_name': 'Matricula de enfasis',
                'verbose_name_plural': 'Matriculas de enfasis',
                'db_table': 'emphasis_enrollment',
                'ordering': ['group__code', 'student__last_name'],
            },
        ),
        migrations.CreateModel(
            name='EmphasisGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('code', models.CharField(max_length=24, verbose_name='Codigo del grupo')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre del grupo')),
                ('capacity', models.PositiveSmallIntegerField(default=25, verbose_name='Cupos')),
                ('weekday', models.PositiveSmallIntegerField(default=1, verbose_name='Dia')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Hora de fin')),
                ('place', models.CharField(blank=True, max_length=120, verbose_name='Lugar')),
                ('status', models.CharField(choices=[('PLANEADO', 'Planeado'), ('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], default='PLANEADO', max_length=10, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Grupo de enfasis',
                'verbose_name_plural': 'Grupos de enfasis',
                'db_table': 'emphasis_group',
                'ordering': ['emphasis__name', 'code'],
            },
        ),
    ]
