# Generated by Django 5.2.17 on 2026-08-23 07:09

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('status', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('TARDE', 'Llegada tarde'), ('EXCUSA', 'Ausencia justificada'), ('RETIRO', 'Retiro anticipado')], db_index=True, default='PRESENTE', max_length=10, verbose_name='Estado')),
                ('minutes_late', models.PositiveSmallIntegerField(default=0, verbose_name='Minutos de retraso')),
                ('excuse_document', models.FileField(blank=True, null=True, upload_to='attendance/excuses/%Y/%m/', verbose_name='Excusa')),
                ('observation', models.CharField(blank=True, max_length=240, verbose_name='Observacion')),
            ],
            options={
                'verbose_name': 'Registro de asistencia',
                'verbose_name_plural': 'Registros de asistencia',
                'db_table': 'attendance_record',
                'ordering': ['student__last_name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Fecha')),
                ('block', models.PositiveSmallIntegerField(default=1, verbose_name='Bloque / hora')),
                ('topic', models.CharField(blank=True, max_length=240, verbose_name='Tema de la clase')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Cerrada')),
            ],
            options={
                'verbose_name': 'Sesion de asistencia',
                'verbose_name_plural': 'Sesiones de asistencia',
                'db_table': 'attendance_session',
                'ordering': ['-date', 'block'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('total_sessions', models.PositiveSmallIntegerField(default=0, verbose_name='Sesiones totales')),
                ('absences', models.PositiveSmallIntegerField(default=0, verbose_name='Inasistencias')),
                ('justified', models.PositiveSmallIntegerField(default=0, verbose_name='Justificadas')),
                ('late_arrivals', models.PositiveSmallIntegerField(default=0, verbose_name='Llegadas tarde')),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Porcentaje de asistencia')),
            ],
            options={
                'verbose_name': 'Consolidado de asistencia',
                'verbose_name_plural': 'Consolidados de asistencia',
                'db_table': 'attendance_summary',
            },
        ),
    ]
