# Generated by Django 5.2.17 on 2026-08-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancesummary',
            options={'ordering': ['student__last_name', 'subject__name'], 'verbose_name': 'Consolidado de asistencia', 'verbose_name_plural': 'Consolidados de asistencia'},
        ),
    ]
