# Generated by Django 5.2.17 on 2026-08-23 07:09

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('code', models.CharField(max_length=48, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=160, verbose_name='Indicador')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor')),
                ('previous_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor anterior')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Unidad')),
                ('icon', models.CharField(default='activity', max_length=40, verbose_name='Icono')),
                ('color', models.CharField(default='#4F46E5', max_length=20, verbose_name='Color')),
                ('category', models.CharField(default='General', max_length=40, verbose_name='Categoria')),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Calculado el')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Indicador del dashboard',
                'verbose_name_plural': 'Indicadores del dashboard',
                'db_table': 'report_dashboard_indicator',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('code', models.CharField(max_length=48, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=180, verbose_name='Nombre del reporte')),
                ('category', models.CharField(choices=[('ACADEMICO', 'Academico'), ('ESTADISTICO', 'Estadistico'), ('ADMINISTRATIVO', 'Administrativo'), ('CONVIVENCIA', 'Convivencia'), ('ASISTENCIA', 'Asistencia')], default='ACADEMICO', max_length=16, verbose_name='Categoria')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('icon', models.CharField(default='bar-chart', max_length=40, verbose_name='Icono')),
                ('parameters', models.JSONField(blank=True, default=list, verbose_name='Parametros')),
                ('default_output', models.CharField(choices=[('PDF', 'PDF'), ('XLSX', 'Excel'), ('CSV', 'CSV'), ('HTML', 'Pantalla')], default='PDF', max_length=6, verbose_name='Formato por defecto')),
                ('allowed_outputs', models.JSONField(blank=True, default=list, verbose_name='Formatos permitidos')),
                ('required_module', models.CharField(default='reports.academic', max_length=80, verbose_name='Modulo requerido')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Catalogo de reportes',
                'db_table': 'report_definition',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eliminado el')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador publico')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Parametros usados')),
                ('output_format', models.CharField(default='PDF', max_length=6, verbose_name='Formato')),
                ('status', models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado'), ('ERROR', 'Con error')], default='EN_PROCESO', max_length=12, verbose_name='Estado')),
                ('rows', models.PositiveIntegerField(default=0, verbose_name='Registros generados')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='Duracion (ms)')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/exports/%Y/%m/', verbose_name='Archivo')),
                ('error_message', models.CharField(blank=True, max_length=320, verbose_name='Mensaje de error')),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ejecutado el')),
            ],
            options={
                'verbose_name': 'Ejecucion de reporte',
                'verbose_name_plural': 'Ejecuciones de reportes',
                'db_table': 'report_execution',
                'ordering': ['-executed_at'],
            },
        ),
    ]
