# Generated by Django 5.2.17 on 2026-08-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('title', models.CharField(max_length=180, verbose_name='Titulo')),
                ('message', models.TextField(blank=True, verbose_name='Mensaje')),
                ('level', models.CharField(choices=[('info', 'Informacion'), ('success', 'Exito'), ('warning', 'Advertencia'), ('danger', 'Alerta')], default='info', max_length=8, verbose_name='Nivel')),
                ('icon', models.CharField(default='bell', max_length=40, verbose_name='Icono')),
                ('module', models.CharField(blank=True, max_length=80, verbose_name='Modulo')),
                ('url', models.CharField(blank=True, max_length=240, verbose_name='Enlace')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Leida el')),
                ('emailed', models.BooleanField(default=False, verbose_name='Enviada por correo')),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
